saros-project/saros

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/preferences/PreferenceConstants.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/preferences/PreferenceInitializer.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/preferences/Preferences.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/Messages.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/messages.properties
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/preferencePages/AdvancedPreferencePage.java

In preparation for the new feature 'Instant Session Start', this patch
introduces a feature toggle, configurable via the user preference store.
While users can already select the feature in Eclipse, via
Preferences -> Saros -> Advanced, it has no effect.
This Patch is a adapted version of parts of the work from
[Patrick Fehling] and [Victor Brekenfeld].
[Patrick Fehling]: https://saros-build.imp.fu-berlin.de/gerrit/#/c/3067/
[Victor Brekenfeld]: https://saros-build.imp.fu-berlin.de/gerrit/#/c/3498/

[FEATURE] Toggle Instant Session Start

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/monitoring/CancelableInputStream.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/DecompressArchiveTask.java

This patch introduces a class, wrapping Input Streams, to check for user
cancellations at each read access and adds this behavior to the
DecompressArchiveTask.
It shortens the response time, till user cancelations are proceded,
while decompressing of large files and removes an old FIXME.

[FEATURE][CORE] Cancelable Input Streams

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties

The contact form on out website saros-project.org is no longer
activated. Add contact should be done through our mailing lists.
Also removes the separate devel mailing list address as it is currently
not used.

[UI][I] Remove contact form address from messages

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationManager.java

Use Collections#singletonList(...) in for the list of annotation ranges
in AnnotationManager#addSelectionAnnotation(...). This improves the
performance of the method as #singletonList(...) only creates a wrapper
for the given element instead of a new list object.
The list contained in the created selection annotation is still mutable
since the general annotation CTOR in AbstractEditorAnnotation copies the
given list of range highlighters instead of using the given list
directly.

[INTERNAL][I] Use a singleton list in #addSelectionAnnotation(...)

---

de.fu_berlin.inf.dpp.intellij/resources/saros.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationQueue.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/QueueAnnotationStore.java

Changes the default annotation behavior to only save the last X
contribution annotations. If a new contribution annotation is added when
this cap is reached, the oldest contribution annotation is removed from
the annotation store.

[FEATURE][I] #115 Add contribution annotation rotation

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/NegotiationFactory.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/TransferType.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/ProjectNegotiationTypeHook.java

In preparation for the new feature 'Instant Session Start', this patch
introduces a new Transfer Type INSTANT and extends the Project
Negotiation Type Hook to negotiate according to the User Preferences.
While users can already select the feature, it has no effect and Project
Negotiation defaults to ARCHIVE.

[FEATURE][CORE] Negotiate Transfer Type Instant

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/InstantIncomingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/InstantOutgoingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/NegotiationFactory.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/stream/AbstractStreamProtocol.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/stream/IncomingStreamProtocol.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/stream/OutgoingStreamProtocol.java

This patch implements the core functionality of Instant Session Start,
which is optional selectable for Project Negotiation. The main scope of
this feature is to decrease the waiting time for users, till the first
files are provided and they can participate in a session.
Deviant to previous approaches, this one uses a file stream based
solution. Compared to using Activities, this provides increased
performance, because of small overheads and better compresion
possibilities, big files support and is for now, not interfering with
existing activity handling code.
This first Version implements a basic prioritisation, by first sending
important eclipse project files, afterwards allways opened files first
and remaining sorted by path hierarchy.
Following features are excluded, to limit this …

[FEATURE][CORE] Introduce Instant Session Start

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/hooks/ISessionNegotiationHook.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/ColorNegotiationHook.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/ProjectNegotiationTypeHook.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/SarosSessionManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/negotiation/hooks/ModuleTypeNegotiationHook.java
de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/net/WhiteboardManager.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/communication/chat/muc/negotiation/MUCNegotiationManager.java

Adds the method ISessionNegotiationHook#setInitialHostPreferences(...).
This method can be used to set initial preferences before the session
negotiation is started. This method is now used in
SarosSessionManager#startSession() to set the initial host preferences
for each hook.
Subsequently removes #tellHostPreferences() as it is no longer needed.

[FIX] #168 Add hook method to set the initial host preferences

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJProjectImplV2.java

Adjusts the module structure check in IntelliJProjectImplV2 to allow
more cases that actually work with the current implementation.
Subsequently moves the checks to separate methods to clean up the CTOR
and adds @throws tags for the exceptions to the CTOR javadoc.
Previously, the restrictions were that the content root of all shareable
modules needed to be located in the project root directory. There were
no restrictions concerning the location of the module file. However, if
the module file is not located in the base directory of the content
root, the creation of the new module as part of the project negotiation
fails on the client side.
The new restrictions for shareable modules are now that
- the content root needs to be located below the project root.
- the module file needs to be …

[INTERNAL][I] Adjust module structure check

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/tree/ContactPopMenu.java

Adds a catch block for IllegalStateExceptions in the ContactPopMenu.
IllegalStateExceptions can be thrown by the IntelliJProjectImplV2 CTOR
when the module structure checks can't find certain needed files. As
these exceptions point towards an error in the local module
configuration that is independent of Saros, a warning is shown to the
user for every module that failed with an IllegalStateException.
Beforehand, these exceptions were uncaught and stopped the contact pop
menu from opening if a faulty module existed.

[INTERNAL][I] Add catch block for IllegalStateException

---

de.fu_berlin.inf.dpp.intellij/META-INF/plugin.xml
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/menu/SarosFileShareGroup.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/menu/ShareWithUserAction.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties

Fixes the names being displayed incorrectly when sharing a module through the context menu. This is done by numbering the available users and using the number as the shortcut. More information can be found in the commit message of b7ad18b982e53584d76eeb2fa1c5779270df2e8b.
25235b28deb7767023c784e2592c3c8e258f0594 and 3493f1fc3c1484e032f1bd116a2a353461c52905 subsequently improve the message of the context menu entry and add shortcuts and descriptions to Saros menu entries.

Fix context menu user name

---

de.fu_berlin.inf.dpp.ui.frontend/html/package.json
de.fu_berlin.inf.dpp.ui.frontend/html/src/components/ComponentTestView/index.jsx
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/IRemoteHTMLTextElement.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/IRemoteHTMLView.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/impl/RemoteHTMLButton.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/impl/RemoteHTMLTextElement.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/impl/RemoteHTMLView.java
de.fu_berlin.inf.dpp/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/STFController.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/ComponentViewTest.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/MainViewTest.java

I introduced a RemoteHTMLTextElement which simply contains text and has
getter and setter for the content. I needed this new Element to test if
a simple click on button, dropdown-button and split-button is working.
So when you click on a button in the ComponentTestView the specified
eventkey will be displayed in a span above the ButtonToolbar whereupon
the assertion takes place.
To dev and debug easier I added jQuery to the ComponentTestView
Change-Id: Id8591a0975973a767ff0d754b5b90055fe3053d6

[STF] Add RemoteHTMLTextElement to test functionality of buttons

---

de.fu_berlin.inf.dpp.ui.frontend/html/src/components/App.jsx
de.fu_berlin.inf.dpp.ui.frontend/html/src/components/BasicWidgetTestView/index.jsx
de.fu_berlin.inf.dpp.ui.frontend/html/src/components/StartSessionWizardView/ChooseFilesStep.jsx
de.fu_berlin.inf.dpp.ui.frontend/html/src/components/Wizard/Step.jsx
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/IHTMLBot.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/impl/HTMLBotImpl.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/IRemoteHTMLTree.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/IRemoteHTMLView.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/impl/RemoteHTMLButton.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/impl/RemoteHTMLTree.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/impl/RemoteHTMLView.java
de.fu_berlin.inf.dpp/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/STFController.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/AddContactTest.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/StartSessionWizardTest.java

To interact with the project file tree in the session dialog I wrote a
RemoteHTMLTree class. In this patch I didn't complete the
StartSessionWizardTest, interaction with the user list is missing for
now.
Change-Id: I6f0aeab9788de999486596a4e6a0b571b709c306

[STF] Add RemoteHTMLTree and use it in StartSessionWizardTest

---

de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/IRemoteHTMLButton.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/IRemoteHTMLView.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/impl/RemoteHTMLButton.java
de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/widget/impl/RemoteHTMLView.java
de.fu_berlin.inf.dpp/test/framework/stf/test/de/fu_berlin/inf/dpp/stf/test/stf/view/html/HtmlBasicWidgetTest.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/StartSessionWizardTest.java

I reused the RemoteHTMLButton to make the ContactListItem clickable. So
now the STF can click on list items in the contact-list. But the wizard
has some more bugs so the test fails until someone fix the issues in the
wizard.

[STF] Add ContactListItem accessible and complete the test

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/context/SarosIntellijContextFactory.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/eventhandler/SessionStatusChangeHandler.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties

Adds a notification that informs the user when a new session is started.
For the host, this contains all users that the session is started with
(usually nobody). For clients, this contains the host of the joined
session.
Adds a notification that informs the user when the current session ends.
This notification also includes the reason the session ended.

[UI][I] Add user notification for session status changes

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorHandler.java

Adds a session check to LocalEditorManager#openEditor(...).
This allows us to avoid false log entries claiming that the open editors
belong to non-shared modules while there is no session.

[FIX][I] Add session check when opening an editor

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorPool.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorHandler.java

The EditorPool was storing Document objects. This is strongly
discouraged by the IntelliJ api documentation as it can lead to memory
leaks. This is explained in more detail in IntelliJ Platform SDK
DevGuide for Documents in the section ["How long does a document
persist?"](http://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/documents.html#how-long-does-a-document-persist).
This problem is easily solved by not holding the document objects
persistently but rather creating them from the stored Editor objects
when they are needed.
Subsequently cleans up the EditorPool, adds more documentation to the
editor pool methods and introduces the usage of NotNull and Nullable
annotations.

[FIX][I] Fix memory leak in EditorPool

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/wizards/AddProjectToSessionWizard.java

To avoid inconsistencies, all open documents are saved on the client
side before starting the project negotiation.
This is more of a temporary solution as this should ideally be handled
by the core logic as well. Such a logic was not needed until now as
Saros/E subverts this issue by closing all open editors on the client
side before the project negotiation starts, thereby saving all modified
files.

[FIX][I] Safe document contents before negotiation

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJProjectImplV2.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/filesystem/ModuleInitialization.java

The module object contained in an IntelliJProjectImplV2 can be refreshed
using the method #refreshModule(). To ensure that the state of the
IProject matches the loaded module, the contained content root is now
also reloaded and subsequently checked against our restrictions.

[FIX][I] Also refresh content roots when refreshing the module object

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AbstractEditorAnnotation.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationStore.java

Adds methods that can be used to clean up the annotation store when
files are moved or deleted. These methods are needed in the upcoming
patches introducing the new logic handling file creations, deletions,
moves and renamings.

[INTERNAL][I] Add methods to handle annotations for moved/deleted files

---

de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/ui/browser/BrowserRunnable.java
de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/ui/browser/EclipseWhiteboardBrowser.java
de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/ui/browser/IWhiteboardBrowser.java

this implementation will be later used in the bridge between the sxe controller of the whiteboard and the browser.
this interface should allow for an eclipse independent implementation of the whiteboard, if for example the whiteboard would be ported to intellij, only the view and an instance of the IWhiteboardbrowser would be needed.
original Gerrit commit: 
[https://saros-build.imp.fu-berlin.de/gerrit/#/c/3550/](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3550/)

[INTERNAL][WB] Added IWhiteboardBrowser and its Eclipse implementation

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/concurrent/watchdog/ConsistencyWatchdogClient.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/concurrent/watchdog/ConsistencyWatchdogServer.java

Adds a check on the host side to ensure that existing checksums for
files are only used if the file still exists locally.
Adds a check on the client side to ensure that checksums for files
that don't exist on both sides don't trigger an inconsistency.

[FIX][CORE] #233 Correctly create ChecksumActivities for missing files

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/StoppableDocumentListener.java
de.fu_berlin.inf.dpp.intellij/test/junit/de/fu_berlin/inf/dpp/intellij/editor/StoppableDocumentListenerTest.java

Moves the functionality of the classes startListening() and stopListening() into setEnabled(boolean).
Removes an empty implementation of an interface class that has become unnecessary with the introduction of the default modifier for interface methods.
Makes the class package-private as it is not accessed outside the package.

Clean up StoppableDocumentListener

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/StoppableEditorFileListener.java

StoppableEditorFileListener.unsubscribe() now correctly drops the held
MessageBusConnection object. If this object is not removed, subsequent
calls  to subscribe(Project) will fail as they think the listener is
already registered.

[FIX][I] Correctly reset connection when unsubscribing editor listener

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/SelectedEditorState.java

Introduces the class SelectedEditorState which can be used to capture
and re-apply which editors are selected in the local IDE. Without such a
logic, opening a new editor as part of the internal Saros logic would
change the currently selected editor, thereby possibly hindering the
user.
Use the logic provided by SelectedEditorState instead of implementing
the logic directly in EditorManager.addProjectResources(IProject).

 [INTERNAL][I] Introduce SelectedEditorState

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/SelectedEditorState.java

Makes the dependency injection in SelectedEditorState static as the
injected objects never change. This avoids additional injections with
every instantiation of SelectedEditorState.
This can help to alleviate potential problems when using annotation injection (too often) as mentioned in #275.

[INTERNAL][I] Make injection in SelectedEditorState static

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java

Moves re-enabling the document listener after applying a text operation
into a finally block to ensure that the listener is always enabled, even
if applying the text operation fails with an uncaught exception.

[FIX][I] Ensure that document listener is enabled after text operations

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorHandler.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/session/SessionUtils.java

Adds a class containing static session utilities. The main benefit of
this utility class is that it can provide certain useful interactions
with the session without requiring the caller to have access to a
session object.
Currently, this class only provides methods to check whether a given
resource is shared or not.
[EDIT: This point is no longer applicable. The need for this utility class stems from the poor separation of which classes should belong to the session context and which to the plugin context. See discussion below.]
This class is currently only used in the IntelliJ part. But as it does not contains any functionality specific to IntelliJ and because it might be useful for other implementations, I added it to the core.
If there are other useful applications for such a static …

 [INTERNAL][I] Add session utilities

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/context/SarosIntellijContextFactory.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorHandler.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/SelectedEditorState.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/StoppableDocumentListener.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/StoppableEditorFileListener.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/VirtualFileConverter.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/VirtualFileConverter.java
de.fu_berlin.inf.dpp.intellij/test/junit/de/fu_berlin/inf/dpp/intellij/editor/StoppableDocumentListenerTest.java

Makes the VirtualFileConverter session independent. The new
implementation now uses the IntelliJ API to get the module objects
needed to convert the VirtualFile.
As a consequence to being independent of the session, the
VirtualFileConverter can now also return resource objects for resources
that are not shared. This means any class using the converter now has to
check whether the returned resource is shared itself.
Adjustments for preexisting usages of the VirtualFileConverter are
included in this commit.
Subsequently makes the VirtualFileListener static for better usability.
Adds utility methods to VirtualFileConverter to convert Saros resources
to VirtualFiles and replaces the existing logic in multiple classes with a
call to the VirtualFileConverter.

[INTERNAL][I] Make VirtualFileConverter static and session independent

---

.idea/google-java-format.xml

Adds google-java-format.xml which enables the google java style
formatting plugin by default for this project if it is installed.

[I] Add xml file enabling google java style plugin by default

---

.gitignore

Adds a .gitignore entry for the directory .idea/sonarlint/ as it is only
used to store results of the local sonar analysis.

[I] Add .gitignore entry for sonarlint directory

---

.idea/misc.xml

Adds a setting that tells the IntelliJ code analyzer to ignore that
instance variables are never assigned if they are tagged with the
PicoContainer "Inject" annotation. This prevents the IntelliJ code
analyzer from incorrectly warning that a injected variable is never
set.
The added section to the misc.xml was created automatically by
IntelliJ.

[I] Add exception for PicoContainer Inject annotation to code analyzer

---

.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/context/SarosIntellijContextFactory.java

Adds some basic codestyle settings for Intellij which are still needed
with the google java style plugin.
Adds import settings to match the google java style:
- Don't use wildcards for normal imports.
- Don't use wildcards for static imports.
- Order imports correctly.
Setting this manually in the Intellij settings is currently needed as
imports are not correctly handled by the google java style plugin.
For more details, see the following issues.
- google/google-java-format#94
- google/google-java-format#236
The used formatting rules were suggested in 263.
Sets the right margin to 100 characters so that it is displayed
correctly in the editor.
Sets indentation and tab size to two spaces as well as the
continuation indentation size to 4 spaces to match the google style.
Otherwise, the …

[I] Add needed codestyle settings

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ProjectNegotiationCollector.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/ProjectNegotiationObservable.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/SarosSessionManager.java

Currently Saros creates a new project negotiation for every individually
added project resource. This leads to multiple concurrent negotiations
per user, which creates more overhead for transportation and user
interaction for every single negotiation. Additionally, it leads to
unexpected behavior because a new negotiation will transfer all files
currently not available on the remote machine, including files from
unfinished negotiation transfers.
This patch ensures that only one project negotiation per user is running
and all new shared resources are queued till all ongoing negotations
finished, before starting a new negotiation with all queued resources /
projects combined.

[CORE] Successive and combined project negotiations

---

de.fu_berlin.inf.dpp.intellij/resources/saros.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorAPI.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/SharedResourcesManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/views/SarosToolbar.java

Adds logic to handle content recovery, meaning the content of an
existing file needs to be adjusted. Previously, this was handled on the
filesystem level, meaning the changes made by the recovery were not
undo-able. This commit introduces a logic to handle content recoveries
on the document level to avoid such issues.
Resolves #285.
Subsequently enables the recovery button as the feature should now be
functional.

[FIX][I] #285 Introduce logic to handle content recovery

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJProjectImpl.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/VirtualFileConverter.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/menu/SarosFileShareGroup.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/tree/ContactPopMenu.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/wizards/AddProjectToSessionWizard.java

Improves the logging when creating IntelliJProjectImpl objects.
Removes the exception from the logging when they are expected and
inconsequential. This is the case when the exception was caused by the
given module not complying with the current restrictions. This is almost
always inconsequential. The only case where this is not expected to
happen is when refreshing the module, which is why the exception is
still logged in such cases.
The exceptions were removed from the log as they were causing many
false-positives when skimming the log for errors/exceptions.
Differentiates between non-compliant module choice handling and real
exception handling where this was not already done correctly.
Exceptions that require different handling and should be logged are
mostly IllegalStateExceptions in …

[INTERNAL][I] Improve logging for IProject creation

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalTextSelectionChangeHandler.java

Removes the declaration of a new SelectionListener through a method
reference assignment and replaces it with an anonymous class. The
method reference assignment requires the interface to be a functional
interface. This is no longer the case with IntelliJ IDEA 2018.3 as
the method defined in SelectionListener now has a default
implementation, meaning the interface now no longer has only exactly
once abstract method.

[FIX][I] Use anonymous class for SelectionListener declaration

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorHandler.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorStatusChangeHandler.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/ProjectAPI.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/SelectedEditorState.java

Moves the subscribing and unsubscribing from the held IntelliJ listener
into the setEnabled(boolean) method. This unifies the functionality.
Furthermore, the previous solution that relied on the enabled flag could
cause consistency issues where events that should be ignored were
triggered while the flag was set to false but the listener was only
notified after the flag was set to true again. This is avoided by always
unsubscribing from the listener when disabling the handler.
Removes wrong nullcheck in
LocalEditorStatusChangeHandler.generateEditorActivatedActivity(...)
where null is a valid value.
Fix LocalEditorHandler.activateEditor(...) to also dispatch activities
when there is no editor selected locally as this is also a valid stat
that should be passed to other participants.
Disables …

Fix local editor status change handling

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/editor/IEditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/core/project/internal/SarosIntellijSessionContextFactory.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/followmode/FollowModeNotificationDispatcher.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/Messages.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/actions/FollowModeAction.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/messages.properties
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/tree/SessionPopMenu.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/views/buttons/FollowButton.java

This PR contains multiple independent commits which should be review separately. Each commit has a commit message that gives some more information.
This PR does not fix the follow mode completely. For the follow mode to function correctly, there still have to be made some adjustments to the logic changing the local viewport and the consistency of the UserEditorState. For this reason, the saros.properties flag disabling the follow mode is not removed yet.
The commits in this PR can be grouped into the following sections:
These commits fix some methods of the EditorManager used by the FollowModeManager.
- [DOC][C] Fix minor javadoc issues in IEditorManager
- [FIX][I] Fix EditorManager.adjustViewport(...)
- [FIX][I] Fix EditorManager.jumpToUser(...)
- [FIX][I] Fix …

Use FollowModeManager to implement Saros/I follow mode functionality

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorAPI.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalViewPortChangeHandler.java

To make the review process easier, the commits should be reviewed (or at least looked at) separately.
Adjusts the logic in LocalViewPortChangeHandler.getLineRange(...) to use
the IntelliJ API to calculate the lines from the given viewport
rectangle instead of calculating it by hand using the line height.
The new logic now uses the logical line positions, meaning it ignores
code folding/soft-wraps. This ensures that both participants see
approximately the same line range, independent of code folding.
Introduces a basic viewport adjustment logic used by the follow mode.
The logic currently always focuses on the center of the remote viewport
range if available or on the center of the remove selection range
otherwise.
There is currently no special handling for the case that the follower …

Fix viewport adjustment logic

---

README.md
docs/support/index.md

I would like to use our already existing [Gitter community]( https://gitter.im/saros-project).
It has the advantage that the fear of contact of users (in channel saros-project/saros/user) is smaller and we are able to use write instant messages and discuss in the developer channel (saros-project/saros) instead of opening an issues that starts with "what do you think about ...". Nonetheless, technical discussions about an issue should be located in the corresponding GitHub issue.
Furthermore the integration of GitHub-"Activies" is a possible alternative to the deprecated GitHub email service.

[DOC] Add gitter badge to support doc and README

---

de.fu_berlin.inf.dpp.whiteboard/frontend/src/shapes/attributesmixin.js

this mixin is added to all the shapes created by fabric.js, it allows certain attributes to be saved and synchronised with the data in Java, additionally it translates the SVG attributes coming from Java to fabric.js attributes that can be applied to the shapes themselves

[INTERNAL][HTML WB] Add attribute mixin

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/communication/extensions/ProjectNegotiationOfferingExtension.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/AbstractIncomingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/AbstractOutgoingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ArchiveIncomingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ArchiveOutgoingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/InstantIncomingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/InstantOutgoingProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/NegotiationFactory.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ProjectNegotiation.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/TransferType.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/NegotiationPacketListener.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/SarosSessionManager.java

TransferType is set via session negotiation mechanism at session start
for the whole session making it unnecessary to transmit it again at 
project negotiation time.

[REFACTOR] Remove unnecessary TransferType usage

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/editor/FollowModeManager.java
de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/permissions/AllParticipantsFollowUserWithWriteAccessTest.java

With the previous logic, either the follower or followee closing a file
would cause the follow mode to end. This commit adjusts the logic so
that the follower and followee can close editors as they please.
If the followee closes the active editor, the new active editor will
automatically be selected by the follower. If there is no active editor
for the followee after closing the previously active editor, the follow
mode is paused until a new editor is opened by the followee.
Subsequently inline stopIfDiverted as it is now only used by one method.
Adjusts the logic in FollowModeManager to allow the follower to close
their last editor while the follow mode is paused, meaning the followee
currently has no open editors. If the followee opens an editor, the
editor is also opened for the …

Fix FollowModeManager issues

---

de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/view/SarosWhiteboardView.java

This should take care of the exception reported in #412. The stack trace indicates that [this specific line](https://github.com/saros-project/saros/blob/91a60b5d4618d589be7c34aafa75b6ffd6dcd896/de.fu_berlin.inf.dpp.whiteboard/src/de/fu_berlin/inf/dpp/whiteboard/view/SarosWhiteboardView.java#L222) was at fault prior to the code reformatting, i.e. the workbench page can be `null`.

Fix whiteboard NullPointerException 

---

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/context/SarosIntellijContextFactory.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/session/SessionUtils.java

SessionUtils provides static access to methods to check whether a given
resource is shared. This check provides the current session object (if
existent), which is why it registers an ISarosSessionLifecycleListener
to update the locally held session object when there are any lifecycle
changes.
This listener was registered in a static block, which is problematic as
java uses lazy evaluation for static blocks, meaning they are only
computed once the object is accessed for the first time.
This leads to problems when the object is only first accessed after the
session has already started as the lifecycle listener will only be
registered at this point. In such situation, the SessionUtils object
will not have a session object even though there is currently a running
session, meaning it reports …

[FIX][I] Fix initialization of SessionUtils

---

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/filesystem/IResource.java
de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/internal/SarosSession.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/core/ui/util/CollaborationUtils.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJResourceImpl.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/VirtualFileConverter.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/negotiation/hooks/ModuleTypeNegotiationHook.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/filesystem/IntelliJWorkspaceRootImpl.java
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/filesystem/ModuleInitialization.java
de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/editor/ServerEditorManager.java
de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/filesystem/ServerResourceImpl.java
de.fu_berlin.inf.dpp.server/test/junit/de/fu_berlin/inf/dpp/server/filesystem/ServerResourceImplTest.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/filesystem/EclipseResourceImpl.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/filesystem/ResourceAdapterFactory.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/model/roster/RosterAdapterFactory.java
de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/model/session/SessionContentAdapterFactory.java
de.fu_berlin.inf.dpp/test/junit/de/fu_berlin/inf/dpp/filesystem/IResourceTest.java

This patch is mainly an updated version of patch
https://saros-build.imp.fu-berlin.de/gerrit/#/c/3291/1
without actually changing the method name of getAdapter

Make return type of IResource.getAdapter(Class) generic and rename it to adaptTo(Class)

---

.idea/codeStyles/Project.xml

Imports the xml file provided on the google java format github page into
the project codestyle.
This is needed as some parts of the formatting rules are not enforced by
the plugin. With the imported rules, they are enforced by the IDE
instead.

[I] Set project codestyle to Google Java Style Code format

---

.travis.yml
de.fu_berlin.inf.dpp.intellij/build.gradle
de.fu_berlin.inf.dpp.intellij/resources/META-INF/plugin.xml
de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java
travis/script/stf/shared_vars.sh

Also removes backwards-compatibility workarounds.
This PR will only build correctly after saros-project/dockerfiles#6 is merged and integrated into the current build environment.

Set 2018.2.6 as minimal required IntelliJ version

---

intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java

Moves opening the created file in an editor after the file creation
activity was dispatched. This is necessary as the Saros otherwise
dispatches the editor opened activity before the file creation activity,
meaning the other participants receive an editor activation activity for
a non-existent resource. This is especially troublesome when the other
participant is following the user that created the file, as they then
automatically try to react to the editor activation activity by also
opening the (non-existent) file.
Fixes #445.
Moves the javadoc concerning the listener behavior from the handler
methods to the javadoc of the listener methods.
Fixes typo in method name 'generateResourceMoveActivity'.
Adds comment for IntelliJ code inspection to ignore the switch case in …

[FIX][I] #445 Enforce correct order of activities after file creation

---

intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java

Adjusts the logic to pass 'null' as the reason when the cancellation was
actively triggered by the user.
Fixes #479.

[FIX][I] #479 Correctly trigger an active negotiation cancel

---

.idea/runConfigurations/saros__runIde_.xml
.idea/runConfigurations/saros__test_.xml
.idea/runConfigurations/saros__test__rerun_tasks.xml
build.gradle

Adds a gradle property to exclude STF self-tests from the test-runner.
This can be useful when trying to use the default 'test' task to run the
tests of all Saros components.
Adds some useful run configurations that are automatically loaded by
IntelliJ on loading the project:
- Adds a "runIDE" config that can be run in parallel
- Adds a "test" config that excludes TestSuites and STF self-tests
- Adds a "test" config that excludes TestSuites and STF self-tests and
always re-runs all test tasks independently of the gradle cache

Add a Gradle property to exclude STF self-tests from the test runner

---

docs/releases/saros-i_0.1.0.md
intellij/resources/META-INF/plugin.xml

Adds release notes for Saros/I 0.1.0.
The page probably contains more information than is necessary as it also includes a section on reporting bugs and on how to use Saros/I. But I was not sure where else to put it. Feedback on the content is appreciated.
Also fixes the link on the index page to correctly point to the html page of the release notes.

[DOC][I] Add release notes for Saros/I 0.1.0

---

intellij/src/saros/intellij/IntellijProjectLifecycle.java
intellij/src/saros/intellij/SarosComponent.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/editor/EditorAPI.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AbstractLocalEditorStatusChangeHandler.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/EditorStatusChangeActivityDispatcher.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/PreexistingSelectionDispatcher.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/ViewportAdjustmentExecutor.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java
intellij/src/saros/intellij/project/ProjectWrapper.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceImpl.java
intellij/src/saros/intellij/ui/actions/AbstractSarosAction.java
intellij/src/saros/intellij/ui/actions/ConnectServerAction.java
intellij/src/saros/intellij/ui/actions/DisconnectServerAction.java
intellij/src/saros/intellij/ui/swt_browser/IntelliJDialogManager.java
intellij/src/saros/intellij/ui/tree/ContactPopMenu.java
intellij/src/saros/intellij/ui/util/DialogUtils.java
intellij/src/saros/intellij/ui/util/NotificationPanel.java
intellij/src/saros/intellij/ui/util/SafeDialogUtils.java
intellij/src/saros/intellij/ui/widgets/progress/ProgressFrame.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/src/saros/intellij/ui/wizards/Wizard.java
intellij/src/saros/intellij/ui/wizards/pages/SelectProjectPage.java
intellij/test/junit/saros/intellij/context/SarosIntellijContextFactoryTest.java
intellij/test/junit/saros/intellij/context/SarosIntellijContextTest.java

This PR is a workaround for the issue #394.
This is only meant as a temporary solution for the upcoming release. Afterwards, this issue will be solved by making Saros/I an application level plugin an explicitly handling the choice which project to share.
THIS IS A RELEASE FIX! DO NOT MERGE ONTO MASTER!
Makes the IntellijProjectLifecycle singleton.
Introduces a wrapper for the held project object as it is changeable
during the plugin lifecycle.
Adds a workaround to replace the old project object when a new project
is opened and the currently held project object is disposed. This is
needed as the internal Saros logic otherwise tries to work on the old
project object which is no longer valid, leading to an assertion error.
This is only a very rudimentary workaround as it still leaves users …

[RELEASE FIX] Add workaround for project switching

---

build.gradle
core/test/junit/saros/net/RosterTrackerTest.java
core/test/junit/saros/net/internal/DataTransferManagerTest.java
eclipse/test/junit/saros/filesystem/IResourceTest.java

Update to PowerMock 2.0.0. This should theoretically add support for
java 9, but from initial testing it looks like the java 9 support is
still a bit buggy.
Updates EasyMock to 3.5.1 as this is the latest release officially
supported by PowerMock 2.0.0.
Subsequently updates jUnit to 4.12. This could not be done previously as
the old mocking libraries required 4.11 or earlier.
Adjusts the test logic initializing Capture objects as they now require
a 'newInstance()' call instead of calling the CTOR.

[BUILD][CORE] Upgrade EasyMock, PowerMock and jUnit

---

intellij/src/saros/core/project/internal/SarosIntellijSessionContextFactory.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorHandler.java
intellij/src/saros/intellij/editor/SelectedEditorStateSnapshot.java
intellij/src/saros/intellij/editor/SelectedEditorStateSnapshotFactory.java
intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalClosedEditorModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/PreexistingSelectionDispatcher.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
intellij/test/junit/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandlerTest.java

This PR starts to move project dependent components to the session context.
This is done in preparation of an upcoming change that would no longer make the project object accessible in the plugin context.
Moving the project into the session context is needed when moving Saros from a project plugin to an application plugin as we can no longer determine which project to run on during the plugin initialization. The project-module combination will be chosen by the user as part of the session start, meaning the project object will only be available in the session context.

Prepare to remove project from plugin context (1 of X)

---

intellij/src/saros/core/project/internal/SarosIntellijSessionContextFactory.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/editor/DocumentAPI.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorHandler.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/viewport/LocalViewPortChangeHandler.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/test/junit/saros/intellij/context/AbstractContextTest.java

Continuation of #451.
Splits off document handling from ProjectAPI and moves ProjectAPI to session context.

Prepare to remove project from plugin context (2 of X)

---

intellij/build.gradle

Removes the workaround adjusting the build classpath used by gradle.
This workaround is no longer necessary as the library conflicts with
JUnit and PicoContainer have been resolved.
Updates the IntelliJ version used when no local installation is provided
to 2019.1.2 (the latest release at the time of writing).
Updates the used version of 'gradle-intellij-plugin' to 0.4.8 as the
current version has issues functioning with IntelliJ versions newer than
2019.1.

[BUILD][I] Remove build classpath workaround

---

intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java
intellij/src/saros/core/ui/eventhandler/XMPPAuthorizationHandler.java
intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/core/util/IntelliJCollaborationUtilsImpl.java
intellij/src/saros/core/util/IntellijCollaborationUtilsImpl.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/ui/SarosToolWindowFactory.java
intellij/src/saros/intellij/ui/actions/AbstractSarosAction.java
intellij/src/saros/intellij/ui/actions/ConnectServerAction.java
intellij/src/saros/intellij/ui/actions/ConsistencyAction.java
intellij/src/saros/intellij/ui/actions/DisconnectServerAction.java
intellij/src/saros/intellij/ui/actions/FollowModeAction.java
intellij/src/saros/intellij/ui/actions/LeaveSessionAction.java
intellij/src/saros/intellij/ui/swt_browser/IntelliJDialogManager.java
intellij/src/saros/intellij/ui/swt_browser/IntellijDialogManager.java
intellij/src/saros/intellij/ui/util/DialogUtils.java
intellij/src/saros/intellij/ui/util/NotificationPanel.java
intellij/src/saros/intellij/ui/util/SafeDialogUtils.java
intellij/src/saros/intellij/ui/util/UIProjectUtils.java
intellij/src/saros/intellij/ui/views/SarosMainPanelView.java
intellij/src/saros/intellij/ui/views/SarosToolbar.java
intellij/src/saros/intellij/ui/views/buttons/ConnectButton.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
intellij/src/saros/intellij/ui/views/buttons/LeaveSessionButton.java
intellij/src/saros/intellij/ui/widgets/progress/ProgressFrame.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/src/saros/intellij/ui/wizards/JoinSessionWizard.java
intellij/src/saros/intellij/ui/wizards/Wizard.java

Continuation of #451 and #452.
Adds a utility to obtains a valid project object for UI purposes. Replaces the plugin context project access of the UI components with calls to the newly added `UIProjectUtils`.
The commits of this PR should be reviewed separately.
<details>
<summary>
Click here to show all commit messages.
</summary>
Removes unused methods to display different types of dialogs.
Adjusts the UI logic related to the toolbar and its contained components
to use the project object passed to the toolbar during its
initialization. This allows the UI components to always use the correct
project object as the reference point when creating new UI components
like dialogs.
Subsequently adjusts the dialog utility classes to accept a project
object as an additional parameter instead of …

Prepare to remove project from plugin context (3 of X)

---

intellij/src/saros/intellij/ui/views/SarosToolbar.java

Uses the theme colors provided by IntelliJ to set the foreground and
background color for the toolbar.
Fixes #535.

[FIX][I] #535 Use theme color for toolbar

---

eclipse/src/saros/ui/Messages.java
eclipse/src/saros/ui/actions/RequestSessionInviteAction.java
eclipse/src/saros/ui/messages.properties
eclipse/src/saros/ui/views/SarosView.java
server/src/saros/server/ServerContextFactory.java

Allows Saros/E to request an invitation to a server session.
Saros/E implements a `JoinSessionRequestHandler` as well, but that is based of the old Eclipse-Server-Prototype and not usable in it's current state. For that reason the "Request Session Invitation" menu item is only shown, if the contact advertises the server feature. Same goes for the action, it is a no-op, if the JID does not belong to a server.
Along with #355 this allows the server to be run completely headless (without using the console).

[E/S][FEATURE] Allow Saros/E to join server session

---

intellij/src/saros/core/project/internal/SarosIntellijSessionContextFactory.java
intellij/src/saros/intellij/editor/DocumentAPI.java
intellij/src/saros/intellij/editor/EditorAPI.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/eventhandler/editor/viewport/LocalViewPortChangeHandler.java

Continuation of #451, #452, and #453.
Adjusts the EditorAPI methods used to modify editor contents to use the
passed project reference for the command processor instead of the
project object held by the session context.
Adjusts the usage of the adjusted methods to request the matching
project object from the module the resource belongs to.
Makes the class EditorAPI static as it is only a utility class that does
not hold a state. Subsequently removes the class from the session
context.

Prepare to remove project from plugin context (4 of X)

---

intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/context/SarosIntellijSessionContextFactory.java

Continuation of #451, #452, #453, and #510.
Moves SarosIntellijSessionContextFactory to the package
'intellij.context'. This was done as the class contains Saros/I specific
dependencies, meaning it can not be moved to the core. For this reason,
it should not remain in the 'core' package.

Prepare to remove project from plugin context (5 of X)

---

server/src/saros/server/filesystem/ServerProjectImpl.java
server/src/saros/server/session/NegotiationHandler.java

Add support for the server to handle `IncomingProjectNegotiation`s now that #355 has finally landed.
Better check commit separately, first commit adds the new functionality.
Second commit is only cleanup of code using newer Java-Features (lambdas, diamond operator).
There is no code to handle ProjectID conflicts in place, because otherwise sharing projects on a later run would not use files already there, and re-sharing new files, when doing partial shares, would not work as well.
This is an issue for later work on the Server, as it will require some more configuration options.
This is for a first alpha release, which should only be run in trusted environments anyway.

[FEATURE][S] Support incoming ProjectNegotiations 

---

core/src/saros/activities/AbstractActivity.java
core/src/saros/activities/AbstractResourceActivity.java
core/src/saros/activities/ChecksumActivity.java
core/src/saros/activities/ChecksumErrorActivity.java
core/src/saros/activities/EditorActivity.java
core/src/saros/activities/FileActivity.java
core/src/saros/activities/JupiterActivity.java
core/src/saros/activities/ProgressActivity.java
core/src/saros/activities/SPath.java
core/src/saros/activities/StopActivity.java
core/src/saros/activities/TextEditActivity.java
core/src/saros/concurrent/management/TransformationResult.java
core/src/saros/misc/xstream/XStreamExtensionProvider.java
core/src/saros/negotiation/FileList.java
eclipse/src/saros/concurrent/undo/UndoManager.java
eclipse/src/saros/editor/EditorManager.java
eclipse/src/saros/monitoring/remote/EclipseRemoteProgressIndicatorImpl.java
eclipse/src/saros/ui/model/session/SessionHeaderElement.java
intellij/src/saros/core/monitoring/remote/IntelliJRemoteProgressIndicatorImpl.java

The hashCode and equals method in the ObjectUtils class from Apache
Commons was marked deprecated and they advise to use the methods from
Java standard libary introduced in Java 7. This replacement was done
using a shell script.

[REFACTOR] Replace deprecated ObjectUtils methods

---

.travis.yml

Each documentation change triggers a ~7min gradle build
and format check. This change skips the build in the earliest
phase of each stage if: only markdown files (with extension .md)
or files in the docs directory are changed.

[BUILD] Skip documentation and markdown during build

---

intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/tree/ContactPopMenu.java

Adjusts the ContactPopMenu to show all open modules grouped by their
project. This is needed to make the plugin context project independent.
Instead of setting the project at plugin initialization, we can instead
use the project selected by the user and set it in the session context.
Replaces a call to IWorkspaceImpl.getProject(String) with directly
instantiating a new IntelliJProjectImpl object as the needed module
object is already present.
Moves text shown to user when interacting with the ContactPopMenu to the
messages.properties file.
Disables the ContactPopMenu menu entry shown when Saros could not find
any (valid) module in the project the host is trying to share.
Otherwise, the user might get confused as it looks like they could still
interact with the menu entry, even though it …

Adjust UI on host side of project negotiation to handle multiple open projects

---

intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/tree/ContactPopMenu.java

Adjusts ContactPopMenu to also show non-shareable modules. Such modules
are disabled in the menu and are displayed in a separate group.
Furthermore, the carry a tooltip explaining that/why they can't be
shared.
Subsequently removes the user notification when encountering a
non-shareable module.
This re-structuring was done to avoid annoying the user with unnecessary
notifications.

[INTERNAL][I] Show non-shareable modules in contact pop menu

---

docs/_data/contribute/sidebar.yml
docs/contribute/processes/release.md

We don't perform the old release process (with multiple roles etc.) anymore.
Therefore I removed the old documentation and created a description of the steps which are required for the release process.

Add release documentation

---

intellij/src/saros/intellij/context/SharedIDEContext.java

Adjusts SharedIDEContext to drop the held preregistered project object.
Otherwise, starting a second session after the first session ended
causes an erroneous warning on the host side as the preregistered
project of the first session is still present.
Adds a null check for applicationEventHandlers and projectEventHandlers
to SharedIDEContext.dispose(). This check is needed as the context can
be disposed without the handlers being initialized when the project
negotiation was canceled on the client side.

Fix issues with SharedIDEContext.dispose()

---

.travis.yml

This reverts commit cbb54e960504cc060d37bda7b33f5795083468d0.
Because of #561

Revert "[BUILD] Skip documentation and markdown during build"

---

core/src/saros/filesystem/IWorkspace.java
eclipse/src/saros/filesystem/EclipseWorkspaceImpl.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceImpl.java
server/src/saros/server/filesystem/ServerWorkspaceImpl.java

Removes the implementation of IntelliJWorkspaceImpl.getProject(String)
and IntelliJWorkspaceImpl.getLocation() as they don't make sense in an
IntelliJ context. Replaces them with throwing an unsupported operation
exception and detailed explanations as part of the javadoc. Also marks
the methods as deprecated.

[INTERNAL][I] Remove implementation of IWorkspace implementation

---

intellij/src/saros/intellij/context/SarosIntellijSessionContextFactory.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorHandler.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/editor/SelectedEditorStateSnapshot.java
intellij/src/saros/intellij/editor/SelectedEditorStateSnapshotFactory.java
intellij/src/saros/intellij/eventhandler/ApplicationEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/ProjectEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalClosedEditorModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AbstractLocalEditorStatusChangeHandler.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/EditorStatusChangeActivityDispatcher.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/PreexistingSelectionDispatcher.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/ViewportAdjustmentExecutor.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java
intellij/test/junit/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandlerTest.java

Removes the last references to the project object held in the session context. This basically marks the end of the refactoring to remove the project object from the plugin context. The rest if just a minor refactoring that can be done when the UI stuff is merged as well.
The PR should by reviewed by going through the commits. Each commit features a commit message giving more details about the content.

Prepare to remove project from plugin context (7 of 7)

---

core/src/saros/negotiation/NegotiationFactory.java
core/src/saros/negotiation/OutgoingSessionNegotiation.java
core/src/saros/session/ISarosSession.java
core/src/saros/session/User.java
core/src/saros/session/internal/ChangeColorManager.java
core/src/saros/session/internal/SarosSession.java
core/src/saros/session/internal/UserInformationHandler.java
core/test/junit/saros/activities/ActivityOptimizerTest.java
core/test/junit/saros/communication/extensions/ActivitiesExtensionProviderTest.java
core/test/junit/saros/concurrent/jupiter/test/util/JupiterTestCase.java
core/test/junit/saros/editor/colorstorage/ColorIDSetTest.java
core/test/junit/saros/misc/xstream/UserConverterTest.java
core/test/junit/saros/negotiation/SessionNegotiationTest.java
core/test/junit/saros/session/internal/ActivityQueuerTest.java
core/test/junit/saros/session/internal/ActivitySequencerTest.java
core/test/junit/saros/session/internal/UserInformationHandlerTest.java
core/test/junit/saros/synchronize/StopManagerTest.java
core/test/junit/saros/test/stubs/SarosSessionStub.java
eclipse/test/junit/saros/editor/internal/ContributionAnnotationManagerTest.java
eclipse/test/junit/saros/feedback/StatisticCollectorTest.java
eclipse/test/junit/saros/project/FileActivityConsumerTest.java

Integration of the User Preference Store into the User Object.
1. this removes the duplicate storage of user color
2. removing (unlikely but possible) data races where a user has already been added to a session but the preference store is not set or user already removed
3. removes some code duplication

[INTERNAL][CORE] Move User Preferences to User Object

---

intellij/src/saros/intellij/ui/views/buttons/ConnectButton.java
intellij/src/saros/intellij/ui/views/buttons/FollowButton.java
intellij/src/saros/intellij/ui/views/buttons/ToolbarButton.java

Manually sets the color of the Saros toolbar popup menu and its entries
using the correct dynamic color references. This reference automatically
changes when the IDE theme is changes, thereby causing the menu color to
change as well.
Also replaces the usage of default swing components in this context with
the jetbrains wrapper, as recommended in the IntelliJ platform SDK.
Fixes #550.
Adds a default border to the Saros toolbar buttons. The color of the
border is determined by the current IDE theme.
Fixes #569.

Fix theme-dependent UI inconsistencies

---

intellij/resources/META-INF/plugin.xml
intellij/src/saros/core/util/IntellijCollaborationUtilsImpl.java
intellij/src/saros/intellij/IntellijProjectLifecycle.java
intellij/src/saros/intellij/SarosComponent.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/context/SharedIDEContext.java
intellij/src/saros/intellij/ui/menu/ShareWithUserAction.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/test/junit/saros/intellij/context/AbstractContextTest.java
intellij/test/junit/saros/intellij/context/SarosIntellijContextFactoryTest.java
intellij/test/junit/saros/intellij/context/SarosIntellijContextTest.java

Adjusts the existing logic to add the needed shared project object to
the SharedIDEContext when a session is started.
Subsequently removes the workaround adding the plugin context project
object to the SharedIDEContext if no other project object is given. The
workaround is no longer needed as all necessary calls starting a session
now correctly set the shared project object.
Makes the Saros/I plugin an application level plugin, meaning a single
instance will be loaded when the application is started. This plugin
instance is shared by all open projects.
Fixes #76. Fixes #394.
Also makes the IntellijProjectLifecycle really a singleton and removes
the project object from the lifecycle.
Subsequently removes the project object from the plugin context as this
is now completely handled by the …

Move Saros/I to application context

---

intellij/src/saros/intellij/ui/actions/FollowModeAction.java
intellij/src/saros/intellij/ui/actions/LeaveSessionAction.java
intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java
intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java
intellij/src/saros/intellij/ui/views/buttons/AbstractSessionToolbarButton.java
intellij/src/saros/intellij/ui/views/buttons/AbstractToolbarButton.java
intellij/src/saros/intellij/ui/views/buttons/ConnectButton.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
intellij/src/saros/intellij/ui/views/buttons/FollowButton.java
intellij/src/saros/intellij/ui/views/buttons/LeaveSessionButton.java
intellij/src/saros/intellij/ui/views/buttons/SimpleButton.java

This fixes the first half (initialization) of #572.
Removes the session lifecycle listener from the FollowModeAction.
Instead, the needed session components are now passed to the execute
command.
This was done to reduce the complexity of the action and remove the
state held by the action, which led to unexpected behaviors.
Adds AbstractSessionToolbarButton to avoid code duplication. The class
can be used by all session buttons.
Also offers the functionality to set the initial state of the button in
case there is already a running session when the button is instantiated.
This is needed as such a case is not covered by the session lifecycle
listener.
Uses AbstractSessionToolbarButtons for all session buttons.
Adds the call to set the initial button state to the button CTORs.
Sets the …

Correctly initialize project-bound Saros UI when there is a running session

---

.idea/gradle.xml
intellij/build.gradle
intellij/src/saros/intellij/ui/menu/SarosFileShareGroup.java
intellij/src/saros/intellij/ui/util/UIProjectUtils.java

Replaces the usage of DataKeys with LangDataKeys. This is necessary as
IntelliJ 2019.2 deprecates the class and largely removes its contents.
Updates the version to build the plugin against to 2019.2.
Subsequently updates the gradle-intellij-plugin to the latest version.
The switch to 2019.2 causes an illegal reflexive access warning to be
displayed when running the plugin locally using 'runIDE'. This seems to
be an issue with IntelliJ and does not seem to influence our plugin.

Upgrade to IntelliJ 2019.2

---

eclipse/plugin.xml
eclipse/src/saros/ui/ImageManager.java
eclipse/src/saros/ui/views/SarosView.java

This time without the plugin.xml magic. The context menu was only shown
when a JID was selected which is only the case when you select something
in the Saros View, to be more specific in the roster.
Restores the original behavior, the only thing that is missing is the
tooltip for the menu entry.

[FIX][E] Fixes #469 by reintroduces missing context menu

---

eclipse/src/saros/SarosEclipseContextFactory.java
eclipse/src/saros/filesystem/EclipseReferencePointManager.java
eclipse/src/saros/ui/util/CollaborationUtils.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java
eclipse/test/junit/saros/filesystem/EclipseReferencePointManagerTest.java

In Saros/E the EclipseReferencePointManager is used for mapping reference points to eclipse projects and also determining eclipse resources given by reference point and relative paths, or SPath.
This PR contains the implementation of the EclipseReferencePointManager and unit tests. The EclipseReferencePointManager is created by the eclipse plugin context and will be filled with eclipse projects and reference points, when a Saros Session is started, like the CoreReferencePointManager.
Features:
- Creates ReferencePoints, given by eclipse projects
- Maps ReferencePoints to eclipse projects
- Returns eclipse projects, given by ReferencePoints
- Returns eclipse resources (IResource, IFile, IFolder),
given by ReferencePoints and ReferencePointRelativePath or SPaths

Introducing EclipseReferencePointManager

---

core/src/saros/activities/SPath.java
eclipse/src/saros/SarosEclipseContextFactory.java
eclipse/src/saros/concurrent/undo/UndoManager.java
eclipse/src/saros/editor/EditorManager.java
eclipse/src/saros/editor/RemoteWriteAccessManager.java
eclipse/src/saros/editor/internal/EditorAPI.java
eclipse/src/saros/filesystem/EclipseReferencePointManager.java
eclipse/src/saros/project/FileActivityConsumer.java
eclipse/src/saros/ui/decorators/SharedProjectFileDecorator.java
eclipse/src/saros/ui/model/session/AwarenessInformationTreeElement.java
eclipse/src/saros/ui/util/CollaborationUtils.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java
eclipse/test/junit/saros/filesystem/EclipseReferencePointManagerTest.java
eclipse/test/junit/saros/project/FileActivityConsumerTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java

This PR contains adjustings of SPath references in Saros/E, because the SPath class can't only return the IReferencePoint and the relative path to the saros resource, but also the saros resources itself (like IFolder, IFile, ...). 
The idea is, that the EclipseReferencePointManager gets the SPath object and determinates Eclipse resources (because in Saros/E the Eclipse resource is determined from the SPath object).
The FileActivityConsumerTest had also to be adjusted.
IMPORTANT: 
Because the PR https://github.com/saros-project/saros/pull/551 has not been merged to the BasedOnReferencePoints branch yet, so this PR shows the Commit (b42539e) "[E] IntroducingReferencePointManager". So please ignore this commit.

Adjusting SPath references in Saros/E with EclipseReferencePointManager

---

eclipse/src/saros/ui/ImageManager.java
eclipse/src/saros/ui/actions/OpenPreferencesAction.java
eclipse/src/saros/ui/views/SarosView.java
eclipse/src/saros/ui/wizards/AddContactWizard.java
eclipse/src/saros/ui/wizards/AddContactsToSessionWizard.java
eclipse/src/saros/ui/wizards/AddResourcesToSessionWizard.java
eclipse/src/saros/ui/wizards/AddXMPPAccountWizard.java
eclipse/src/saros/ui/wizards/ColorChooserWizard.java
eclipse/src/saros/ui/wizards/ConfigurationWizard.java
eclipse/src/saros/ui/wizards/CreateXMPPAccountWizard.java
eclipse/src/saros/ui/wizards/EditXMPPAccountWizard.java
eclipse/src/saros/ui/wizards/StartSessionWizard.java

Such ImageDescriptors can be generated as needed so there is no need to
store them somewhere. 
In addition when an image cannot be found a default one is returned in
addition with a warning message in the log file. This fixes the issue
where Eclipse will not even start when an image is missing due to an NPE
in the static initializer on some classes (in this case some Chat
Stuff).

[INTERNAL][E] Removes static ImageDescriptos from ImageManager

---

eclipse/src/saros/ui/messages.properties

misleading
Fixes issue #65. Took only several years to change a string after a
feature got removed because it was not working as intended.

[FIX][E] #65 Warning dialog upon reusing an existing project is

---

eclipse/src/saros/SarosEclipseContextFactory.java
eclipse/src/saros/StartupSaros.java
eclipse/src/saros/ui/actions/ChangeXMPPAccountAction.java
eclipse/src/saros/ui/eventhandler/ConnectingFailureHandler.java
eclipse/src/saros/ui/util/XMPPConnectionSupport.java
eclipse/src/saros/ui/wizards/AddXMPPAccountWizard.java
eclipse/src/saros/ui/wizards/ConfigurationWizard.java
eclipse/src/saros/ui/wizards/CreateXMPPAccountWizard.java

Adds a central class that is now responsible for connection attempts.
This should help to prevent certain misuse, e.g disconnecting an active
session without any warning.
In addition this patch removes the inheritance between the
XMPPAddAccountWizard and the SarosConfigurationWizard.

[INTERNAL][E] Adds central connection access point for the UI

---

intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java
intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java
intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java
intellij/src/saros/intellij/ui/views/SarosMainPanelView.java
intellij/src/saros/intellij/ui/views/SarosToolbar.java
intellij/src/saros/intellij/ui/views/buttons/AbstractSessionToolbarButton.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
intellij/src/saros/intellij/ui/views/buttons/FollowButton.java
intellij/src/saros/intellij/ui/views/buttons/LeaveSessionButton.java

Correctly disposes the project-bound Saros UI so that it can be garbage collected after the project was closed.
The objects are correctly garbage collected after this change (tested with looking at the heap with the debugger).
This fixes the second half of #572.
Makes AbstractSessionToolbarButton implement Disposable (IntelliJ
interface, not PicoContainer).
The basic logic to dispose the abstract button just removes the session
lifecycle listener. The class also offers an abstract method to allow
sub-classes to disposing their components when the button is disposed.
Registers the button to be disposed when its project is disposed.
Adjusts SessionAndContactsTreeView and its components to be disposed
when their project is disposed.
Adds javadoc to SarosMainPanelView stating and explaining …

Dispose project-bound Saros UI to avoid memory leaks

---

intellij/src/saros/intellij/editor/EditorManager.java

Adjusts the logic to send the current user editor state to no longer
send the state of the joined user. This was done as the session of the
joined user might not have been set up completely at this point.
Instead, the state of the joined user will be send as part of the
resources added call. This change is made in a separate commit.
Moves the methods to send the user editor state out of the session
listener as they are now also needed outside the listener.
Adjusts the logic of EditorManager#addProjectResources(IProject) to also
send the user editor state for any editors belonging to the added
module.
Fixes #581.
Ensures that the correct active editor is set after initializing the
user editor state for added modules.

Fix initial user editor state

---

eclipse/src/saros/Saros.java
eclipse/src/saros/SarosEclipseContextFactory.java
eclipse/src/saros/preferences/EclipsePreferenceInitializer.java
eclipse/test/junit/saros/feedback/StatisticCollectorTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java

Preferences in Eclipse are quite complex. Without going too deep in
detail we have an issue regarding the preference scope in Eclipse. It is
currently scoped to the workspace and not the application.
This commit also fixes an issue with test cases that will fail if
assertions are enabled.

[INTERNAL][E] Adds comments regarding Preferences

---

eclipse/src/saros/editor/internal/AnnotationModelHelper.java
eclipse/src/saros/editor/internal/ContributionAnnotationManager.java
eclipse/test/junit/saros/editor/internal/ContributionAnnotationManagerTest.java

This patch fixes the last outstanding issues regarding #32.
Annotations that were split are now correctly inserted to the history
and so correctly removed.
This patch introduces a new method to the annotation helper as well as
it reduces LOC in the ContributionAnnotationManager.

[FIX][E] #32 Splitting annotations do not honor the history

---

eclipse/src/saros/ui/actions/ChangeXMPPAccountAction.java
eclipse/src/saros/ui/eventhandler/ConnectingFailureHandler.java
eclipse/src/saros/ui/preferencePages/GeneralPreferencePage.java
eclipse/src/saros/ui/util/XMPPConnectionSupport.java
eclipse/src/saros/ui/wizards/ConfigurationWizard.java
intellij/src/saros/intellij/ui/actions/ConnectServerAction.java
server/src/saros/server/ServerLifecycle.java
stf.test/test/saros/stf/test/account/AccountPreferenceTest.java
stf/src/saros/stf/server/rmi/controlbot/manipulation/impl/AccountManipulatorImpl.java
stf/src/saros/stf/server/rmi/superbot/component/menubar/menu/submenu/impl/SarosPreferences.java
ui/src/saros/ui/browser_functions/SetActiveAccount.java
ui/src/saros/ui/core_facades/ConnectionFacade.java

This patch introduces the usage of the new XMPPStore API.
Renaming UI buttons is not done yet as changing UI values is likely to
crash the whole STF.

[INTERNAL][UI] Use new XMPPStore API

---

eclipse/src/saros/ui/wizards/ConfigurationWizard.java
eclipse/src/saros/ui/wizards/pages/EnterXMPPAccountWizardPage.java

[UI][E] Moves information from ENterXMPPAccountWizardPage
This information is only needed for the configuration wizard. It is very
confusing if you open the page in stand-alone mode and reading "If you
already have a XMPP account ..." 
I am guessing I would have used Create-Account instead of Add-Account if
I do not own a XMPP account.

[UI][E] Moves information from EnterXMPPAccountWizardPage

---

eclipse/src/saros/ui/eventhandler/ConnectingFailureHandler.java
eclipse/src/saros/ui/util/XMPPConnectionSupport.java

[INTERNAL][E] Addresses FIXME in ConnectinFailureHandler
Added an option to retrieve the current account that was used for
connecting. Another option would have been to modify the ConnectHandler.
As IntelliJ currently have a very minimalistic set of connection option
the necessary logic was put into the XMPPConnectionSupport instead.

[INTERNAL][E] Addresses FIXME in ConnectingFailureHandler

---

eclipse/src/saros/ui/BalloonNotification.java
eclipse/src/saros/ui/widgets/viewer/project/ResourceSelectionComposite.java

This fixes issue #31. Changed the default anchor as my current testing
did not produce the result shown in the picture of the issue entry, e.g
the notification was shown outside of the WizardPage.

[FIX][E] #31 Balloon after saving partial sharing selection is too big

---

eclipse/src/saros/ui/BalloonNotification.java
eclipse/src/saros/ui/views/SarosView.java

This fixes issue #28.
The popups are now displayed at the bottom of the view. As there was not
functionality to specify the "hooking point" an invisble widget was
added to the bottom of the view which is used as reference point.

[FIX][E] #28 Make Balloons not overlap editorparts

---

eclipse/src/saros/ui/widgets/wizard/ProjectOptionComposite.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java
eclipse/src/saros/ui/wizards/pages/EnterProjectNamePage.java

This patch introduces a feature that will remember the settings made
when selecting the destination for incoming projects.
The settings will then be applied during a new session and so it is not
necessary to enter the names of the local projects over and over again.

[FIX][E] #66 Reuse existing project mappings 

---

eclipse/src/saros/project/SharedResourcesManager.java
eclipse/src/saros/ui/eventhandler/SessionStatusRequestHandler.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java
eclipse/src/saros/ui/wizards/pages/EnterProjectNamePage.java

The IReferencePointManager (CoreReferencePointManager) was still used in Saros/E...
In this PR, I replaced the using of IReferencePointManager (CoreReferencePointManager) by the EclipseReferencePointManager...

[E] Detaching IReferencePointManager in Saros/E

---

intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java

Adjusts IntelliJProjectImpl.equals(Object) and .hashCode() to directly
use the respective method of the held Module object. This is possible as
Module objects are singleton across the IDE lifecycle, i.e. a module
will always be represented by a single, unique Module object.
This change allows us to differentiate modules with the same name
belonging to different projects. This fixes #488.
Subsequently adjusts IntelliJProjectImpl.toString() to also include the
project the module belongs to.

[FIX][I] #488 Adjust module comparison for multiple open projects

---

core/src/saros/session/ISarosSession.java
core/src/saros/session/internal/SarosSession.java
intellij/src/saros/intellij/context/SarosIntellijSessionContextFactory.java
intellij/src/saros/intellij/eventhandler/project/ProjectClosedHandler.java
intellij/src/saros/intellij/runtime/IntelliJSynchronizer.java

Adds the logic to report a project as disposed to the session. This
causes all activities for such projects to be dropped.
This functionality is useful to prevent the session from trying to apply
activities to disposed (closed) projects.
As this logic is currently only used by Saros/I, it is not set up to
handle disposed partial-sharing resources. If this would be come useful
at some point, the logic should be adjusted to also hold a mapping for
disposed partially-shared resources.
Adjusts IntelliJSynchronizer to catch and log ProcessCanceledExceptions
which are thrown when a synchronous execution on the EDT is interrupted.
Adds a listener to end the session when the project containing the
shared module is closed. The listener also reports the modules of the
project as disposed to the …

End session when project of shared module is closed

---

eclipse/src/saros/editor/EditorManager.java

This patch fixes issue #392.
As it turns out we hook into partBroughtOnTop events. What is going on
is something like:
EditorManager#jumpToUser
For what reason ever when opening / switching to the new editor a
partBroughtOnTop event may be fired containing the current focused
editor. The logic transforms this into an editorActivated event which
gets passed back to the FollowModeManager before the
FollowModeManager#follow method is even finished. The result is that the
FollowModeManager state is changed to not following and after that it
will report that it has start following.
This patch will drop editorActivated events for editors that are
currently the active editor.

[FIX][E] #392 EditorManager may fire duplicate partActivated events

---

core/src/saros/editor/ISharedEditorListener.java
core/src/saros/editor/SharedEditorListenerDispatch.java

Was not used anywhere, nor was the method actually triggered by any
logic.

[INTERNAL][CORE] Removes deprecated method from ISharedEditorListener

---

eclipse/src/saros/SarosEclipseContextFactory.java
eclipse/src/saros/ui/preferencePages/GeneralPreferencePage.java

This feature was disable since Saros Version 14. However it seems that
the patch was not merged back after the release so this patch will
disabled it again so it is not accidently shipped.
Clarification: This feature is BROKEN as HELL, if you turn it on it is likely to freeze the IDE sooner or later.

[INTERNAL][E] Disable Concurrent Undo Feature

---

eclipse/src/saros/Saros.java

When the stop method of the AbstractUIPlugin it is almost always the case that the UI thread is "not available" anymore because stop is called because the IDE shuts down.
This commit monitors the workbench and triggers a proper shutdown while the UI thread is still available.
In general this commit prevents mass warning logging when the user
simply clicks the close button of the Eclipse IDE.
This patch also adds some safeguards to AbstractContextLifecyle.

[INTERNAL][E] Allows Saros to properly shutdown

---

core/build.gradle
core/src/saros/net/upnp/internal/UPnPServiceImpl.java
eclipse/build.gradle

This fixes #98 by implementing the missing functionality to handle
multiple IGD that support lease durations.
This patch also fixes and issue I have found using a FritzBox. It seems
that the Fritzbox is renaming the MappingDescription and so we would
face problems if want to apply the mapping again without removing it
first (e.g due program crash).

[FIX] #98 UPnPTest#testDispose() Fails if Assertions are Enabled

---

core/build.gradle
eclipse/build.gradle

Removes the gradle config enabling assertions for testing from the core
and eclipse config. These settings are not needed as enabled assertions
is the default behavior.

[BUILD] Remove unnecessary config enabling build assertions

---

intellij/src/saros/intellij/ui/wizards/Wizard.java
intellij/src/saros/intellij/ui/wizards/pages/NavigationPanel.java
intellij/src/saros/intellij/ui/wizards/pages/TextAreaPage.java

Replaces the direct usage of UI classes with the matching wrappers
provided by IntelliJ.
This was solely done by following the IntelliJ suggestions.
This solves an open issue where the text color of the dialog showing
which files of the existing module have to be adjusted to use it for an
incoming project negotiation was not adjusted correctly when using
different IDE themes. This logic is automatically provided by the
IntelliJ color class wrapper.

[UI][I] Use IntelliJ UI wrapper classes

---

eclipse/plugin.xml
eclipse/src/saros/ui/expressions/ContactPropertyTester.java
eclipse/src/saros/ui/views/SarosView.java

This patch fixes #19. The option(s) to invite an offline contact is no
longer possible.

[FIX][E] #19 Add Contact to session is enabled for offline contacts

---

core/src/saros/net/IConnectionManager.java
core/src/saros/net/IPacketInterceptor.java
core/src/saros/net/IReceiver.java
core/src/saros/net/ITransmitter.java
core/src/saros/net/internal/BinaryChannelConnection.java
core/src/saros/net/internal/DataTransferManager.java
core/src/saros/net/internal/IBinaryXMPPExtensionReceiver.java
core/src/saros/net/internal/IByteStreamConnection.java
core/src/saros/net/internal/IByteStreamConnectionListener.java
core/src/saros/net/internal/XMPPReceiver.java
core/src/saros/net/internal/XMPPTransmitter.java
core/test/junit/saros/net/internal/BinaryChannelConnectionTest.java
core/test/junit/saros/net/internal/DataTransferManagerTest.java
core/test/junit/saros/test/fakes/net/NonThreadedReceiver.java
core/test/junit/saros/test/fakes/net/ThreadedReceiver.java
eclipse/src/saros/feedback/DataTransferCollector.java
eclipse/test/junit/saros/feedback/StatisticCollectorTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java
stf/src/saros/stf/server/StfRemoteObject.java
stf/src/saros/stf/server/rmi/controlbot/manipulation/impl/NetworkManipulatorImpl.java

This is just a cleanup, removing transfer logic out of the DTM which already implements the IConnectionManager, indicating that this class is no longer responsible for data transfer.

[INTERNAL][CORE] Moves logic from DTM to XMPPTransmitter and XMPPReceiver

---

core/src/saros/net/stun/internal/StunServiceImpl.java
core/src/saros/preferences/PreferenceInitializer.java

The stun discovery often throws a PortUnreachableException that the ICMP
port is unreachable. This does not seem to hinder the functionality, but
is still logged as a warning.
This warning leads to confusion for the users when reporting bugs as
they assume that the log entry (including the stacktrace) is the cause
of whatever issue they are having with Saros.
To avoid this wrong assumption (and users only sending this part of the
stacktrace), the log level is reduced to info and the stacktrace is
dropped.

[LOG][CORE] Drop log level of PortUnreachableException

---

intellij/src/saros/intellij/negotiation/ModuleConfiguration.java
intellij/src/saros/intellij/negotiation/ModuleConfigurationInitializer.java
intellij/src/saros/intellij/negotiation/ModuleConfigurationProvider.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/util/SafeDialogUtils.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java

Adds the option for a non-blocking yes/no dialog that accepts a runnable
that is run if the 'Yes' option is chosen.
Adds the data holder class ModuleConfiguration. The class encapsulates
the parsing of the module configuration option contained in the
additional project options transferred as part of the project
negotiation data.
Adjusts the ModuleConfigurationInitializer to also offer the user to
load the module config of the host in case an existing module is used
but the config differs from the received one.
This functionality is now useful as we no longer transfer the module
file.
Subsequently adjusts the logic applying the config to newly created
modules to also use the ModuleConfiguration data holder class.
Also adjusts ModuleConfigurationProvider.split(String) to accept (and …

Offer module configuration adjustment for existing modules

---

intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java

Correctly resets the icon of the consistency button to the "consistent
state" version on session end. This is done to ensure that the button is
correctly reset when the session is ended while the client was in an
inconsistent state.

[FIX][I] Correctly reset icon of consistency button on session end

---

eclipse/src/saros/concurrent/undo/UndoManager.java
eclipse/src/saros/editor/EditorActivityDelayer.java
eclipse/src/saros/editor/EditorManager.java
eclipse/test/junit/saros/SarosEclipseContextFactoryTest.java
eclipse/test/junit/saros/SarosEclipseContextTest.java
eclipse/test/junit/saros/test/mocks/EclipseMocker.java
eclipse/test/junit/saros/test/mocks/PrepareEclipseComponents.java

They are already "optimized" during sending an execution. However if you
have a fast network and a fast computer selecting text will equal
running a computer game, consuming the resources of a CPU die and
depending on the garbage collection additional dies.
This patch introduced a delayer which currently starts to reduce the
number of Selection Activities.

[INTERNAL][E] Throttle generation of editor related activities

---

intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/wizards/pages/moduleselection/ModuleTab.java

Adjusts the project negotiation dialog to allow the accepting side
choose a module name different from the name on the host side. This is
not possible as we no longer share the module file.
Subsequently adds a check to the option to create a new module to
disallow to continue the dialog when a module with the chosen name
already exists in the chosen project. Previously, such a situation would
lead to the negotiation aborting with an error message.
Adjusts the dialog to accept a project negotiation to only show fields
as invalid if they are currently being evaluated. Otherwise, fields are
marked as invalid that are not used for the currently chosen mode, which
could lead to confusion.

Allow different module names

---

intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java

Removes the held reference to the module name and replaces it by
dynamically requesting the name from the module object. This change is
needed as module names can change during runtime, but the module is
always represented by the same object. This allows us to better handle
such name changes.
Adjusts the module comparison in
IntelliJProjectImpl.getProjectRelativePath(VirtualFile) to use the
module objects directly. Previously, the module names were compared. As
already mentioned in the changes reworking the equals method, the name
can not be used as a unique identifier when multiple project are
allowed.

Remove module name reference in IntelliJProjectImpl

---

build.gradle

Adjusts the base build.gradle configuration in order to correctly
configure the modules creates from the configurations. Adds the folders
'bin', 'lib', and 'libs' as excluded resources. This is needed as they
contain compiled resources (libraries or class files), which otherwise
would be found by the IntelliJ search, polluting the search results.
Fixes #490.

[BUILD] Adjust gradle config to correctly configure modules

---

core/src/saros/session/ISarosSession.java
core/src/saros/session/internal/SarosSession.java
core/test/junit/saros/test/stubs/SarosSessionStub.java
eclipse/src/saros/ui/util/CollaborationUtils.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java

After rebasing the `BasedOnReferencePoints`, I got many conflicts in PR https://github.com/saros-project/saros/pull/650. So I reimplemented the small changes again:
Original Message:
This is the last PR regarding adjusting Saros/E to ReferencePoints.
This PR contains a small extension of the ISarosSession:
- isShared(IReferencePoint referencePoint): bool
It checks if a reference point is shared.
This extension is needed for adjusting the CollaborationUtils and AddProjectToSession classes in Saros/E.

[Core][E] Check if ReferencePoint is shared

---

eclipse/src/saros/ui/wizards/ConfigurationWizard.java

Flips the check to now correctly request the existing account if it is
detected.

[FIX][E] #676 Fix check whether account exists in configuration wizard

---

intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java
intellij/src/saros/intellij/context/SharedIDEContext.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/util/NotificationPanel.java
intellij/src/saros/intellij/ui/util/UIProjectUtils.java

Adjusts the notification panel logic to use the session project or, if
no such project is available, use the last focused project. This
guarantees that a project is always specified to guarantee that the
notification is always displayed as a pop-up.
Indirectly fixes a bug where the old logic requesting the Project object
directly from the plugin context was still used in
UIProjectUtils.getProjectFromSession(). This lead to the method always
returning null, even if a shared project was available.
Adds a method to check whether the shared IDE context is completely
initialized. This is needed as it is not guaranteed that the
notification logic is only called after the initialization. This is only
a workaround. The logic should be improved to better handle calls in the
uninitialized state. …

Fix version mismatch notification and notification utils bug

---

core/src/saros/negotiation/InstantIncomingProjectNegotiation.java
core/src/saros/negotiation/InstantOutgoingProjectNegotiation.java
core/src/saros/negotiation/stream/IncomingStreamProtocol.java
core/src/saros/negotiation/stream/OutgoingStreamProtocol.java

To simplify code and avoid potential resource leaks use
try-with-resources Statement in Instant Session Start code.

[CORE] Use try-with-resources in ISS

---

intellij/src/saros/intellij/preferences/colors/LocalSarosAnnotationColorsPage.java

IntelliJ IDEA always requires the usage of Unix line separators,
independent of the underlying operating system. The demo text was still
using system-dependent separators, leading to the color settings page
not loading under Windows.
Fixes #696.

[FIX][I] #696 Use Unix line separator for color demo text

---

intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/filesystem/Filesystem.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java
intellij/src/saros/intellij/ui/menu/ShareWithUserAction.java

Removes Nullable annotation from FileSystem.runReadAction and
runWriteAction as we can't make any statement about the return value of
the computation. Whether the returned value can be null or not depends
solely on the contents of the computation itself. This makes the
annotation not very helpful.
Wraps any calls to methods of FileIndex or its implementations in a read
action to comply with the IntelliJ access guidelines and avoid illegal
access assertion errors.

Wrap calls to FileIndex methods in a read action

---

intellij/src/saros/intellij/IntellijApplicationLifecycle.java
intellij/src/saros/intellij/SarosComponent.java

Renames IntellijProjectLifecycle to IntellijApplicationLifecycle to
reflect that it is now application-bound. This change was made some time
ago but the class name and javadoc were not updated accordingly.

[REFACTOR][I] Rename project lifecycle to show application bond

---

docs/releases/saros-i_0.2.1.md
intellij/resources/META-INF/plugin.xml
intellij/src/saros/intellij/negotiation/ModuleConfigurationInitializer.java
intellij/src/saros/intellij/negotiation/ModuleConfigurationProvider.java
intellij/src/saros/intellij/negotiation/ModuleUtils.java

Adjusts the URI parsing used when reading the source root configuration
of the shared module to also work with Windows paths.
Subsequently adjusted ModuleConfigurationProvider to also use the URI
approach instead of relying on the VirtualFiles of the roots. This was
done to unify the shared root state. When using the VirtualFiles, roots
that are registered with the module but don't have a valid
representation in the file system (and therefore don't have a valid
VirtualFile representation) would be ignored. Such roots are now also
transmitted by the host.
Subsequently moved the logic to parse and relativize root paths to
ModuleUtils so that it can be used by ModuleConfigurationProvider and
ModuleConfigurationInitializer.
Fixes #703.

[FIX][I] #703 Adjust URI parsing to work with Windows paths

---

.idea/compiler.xml
.idea/gradle.xml

Opening the Saros project without the ui packages in IntelliJ changes the gradle.xml file and compiler.xml.

[BUILD] Remove ui package from gradle/compiler.xml

---

intellij/build.gradle

Updates the IntelliJ version used locally to build Saros/I when no
installation is linked to 2019.2.3.
This was done after looking at the incompatibility notes, trying it out
locally, and doing some smoke testing to determine whether the update to
2019.2.3 introduces any issues. There did not appear to be any issues.
Subsequently updates the gradle intellij plugin to version 0.4.10.

[BUILD][I] Update developer build version to 2019.2.3

---

intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/filesystem/IntelliJReferencePointManager.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/test/junit/saros/intellij/filesystem/IntelliJReferencePointManagerTest.java

This PR contains the introducing of the IntelliJReferencePointManager in Saros/I.
The idea is, that the IntelliJReferencePointManager stores the mapping of `IReferencePoint`s to IntelliJ `Module`s.
In additionally, it is able to create `IReferencePoint`s (like the EclipseReferencePointManager), given by a Module or VirtuaFile, and to resolve resources given by `IReferencePoints` and relative paths.
With resources is meant by `VirtualFiles` and Saros resources. 
The resolving of Saros resources with `IReferencePoints` and relatives path is needed to the resources from `SPath` (next PR).

[I] Introducing IntelliJReferencePointManager

---

intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java

Split resource deletion handling into separate methods for file and
folder deletions. This was done in preparation for the adjustment of the
folder deletion logic to explicitly handle child resources as this new
logic requires additional calls to the file deletion logic.
Moves the creation of a VirtualFileFilter to separate method. This is
done as it will also be used by the logic iterating the contents of the
deleted folder.
Adjusts LocalFilesystemModification.generateFolderDeletion(...) to
explicitly create deletion activities for the contained resources. This
ensures that the resource deletion of the child resources is handled
correctly for all other participants. Furthermore, it ensures that the
local state of all deleted child resources is also correctly torn down.
This is done as a …

Explicitly handle child resources when deleting folders

---

intellij/src/saros/intellij/eventhandler/project/ProjectClosedHandler.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/menu/ShareWithUserAction.java
intellij/src/saros/intellij/ui/messages.properties

Adjusts the logic creating the IntelliJProjectReference in
ShareWithUserAction to catch and correctly handle the
IllegalArgumentException thrown in case an illegal module is selected to
be shared.

Fix module creation failure handling

---

core/src/saros/negotiation/InstantIncomingProjectNegotiation.java
core/src/saros/negotiation/InstantOutgoingProjectNegotiation.java
core/src/saros/negotiation/stream/OutgoingStreamProtocol.java

Instant Session Start uses a stream initiated via Smack to send files.
In some cases close() on this stream will not flush remaining data and
stop the transmission before all data has been sent.

[CORE] Instant Session Start: Await Transfer End

---

intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorHandler.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/eventhandler/ApplicationEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/ProjectEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalClosedEditorModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/PreexistingSelectionDispatcher.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/IntelliJReferencePointManager.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
intellij/test/junit/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandlerTest.java

This PR contains adjustings of SPath references in Saros/I, because the SPath class can't only return the IReferencePoint and the relative path to the saros resource, but also the saros resources itself (like IFolder, IFile, ...).
The idea is, that the IntelliJReferencePointManager gets the SPath object and determinates IntelliJ and Saros resources

Adjusting SPath references in Saros/I with IntelliJReferencePointManager

---

gradle/wrapper/gradle-wrapper.properties

Adjusts the gradle wrapper configuration to also download the gradle
sources. Downloading the sources as well allows IDEs to automatically
link the documentation for gradle methods used in the build.gradle
files.

[BUILD] Include grade sources when downloading gradelw

---

intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/filesystem/IntelliJResourceImpl.java

Replaces the static references to the content root in
IntelliJProjectImpl with dynamic requests. This ensures that the correct
content root is used after it was moved.
Adjusts LocalFilesystemModificationHandler to filter out folder move
activities for the content root of the shared module. This allows the
participants to freely move/rename the shared module without causing
desyncs.
Fixes #684.
Adjusts the logic to not send activities when the module file is moved
back into the shared module.
This logic is currently enough to handle the special case that the
module file of a shared module is moved outside of the shared module.
This is no longer true once multiple modules can be shared at the same
time, as we then also have to handle the case where the module file is
moved into a different …

Handle resource move corner cases

---

core/src/saros/net/internal/BinaryChannelConnection.java

To reduce user input latency, the network socket is configured to send
a new TCP packet each time flush() is called on its provided stream.
The downside is more packets are generated, thus increasing overhead for
additional headers, processing time and thelikelihood of packet loss.
The saros network protocol uses four message types, three of which
describe the payload and one the DATA type carrying the payload. Since
the describing messages are only useful for handling the payload, they
do not need to be sent separately.

[CORE] Network: Reduce Number of TCP Packets

---

intellij/build.gradle

Adjusts the Saros/I build script. This is necessary to allow the project
to be imported cleanly into Eclipse.

[BUILD][I] Fix Saros/I build script to allow import into Eclipse

---

core/src/saros/account/XMPPAccountStore.java
core/src/saros/editor/colorstorage/ColorIDSetStorage.java
core/src/saros/misc/xstream/XStreamExtensionProvider.java
core/src/saros/misc/xstream/XStreamFactory.java
core/test/junit/saros/misc/xstream/ReplaceableConverterTest.java
core/test/junit/saros/misc/xstream/ReplaceableSingleValueConverterTest.java
core/test/junit/saros/misc/xstream/SPathConverterTest.java
core/test/junit/saros/misc/xstream/UserConverterTest.java
core/test/junit/saros/negotiation/FileListTest.java

Adds XStreamFactory as a factory class providing XStream objects whose
security framework was already setup to our needs. The security
framework is set up to allow the following objects:
- null
- Java primitives and their wrappers
- Class extending 'Collection'
- Classes extending 'Map'
- String
- Classes in any package starting with 'saros.**'
This should currently allow any existing logic to function as before.
The security framework was introduces to prevent misuse of the
functionality. See https://x-stream.github.io/security.html
Base for fixing #209.
Adjusts the core logic to always use the XStreamFactory to obtain
XStream objects.
This change was also applied to internal usages of XStream that do not
handle any network messages. It is not strictly necessary here but does
not hurt …

Add XStream Security Framework Setup

---

intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java

Avoid the usage of IResource.getFullPath() and getLocation() as they
don't accurately represent the actual module structure. By just
appending the relative path to the module name, this suggest a certain
module structure that must not necessarily be present.
This inaccurate path could create confusion with the user. To avoid
this, I would suggest the usage of the format "MODULE_NAME -
RELATIVE_PATH". This should still give the user ample information to
identify the correct resource in the filesystem.

[INTERNAL][I] Avoid usage of IResource methods using project paths

---

stf/src/saros/stf/server/rmi/controlbot/manipulation/IAccountManipulator.java
stf/src/saros/stf/server/rmi/controlbot/manipulation/impl/AccountManipulatorImpl.java

The behavior of the method is same as of commit
e3ac006ced542c3dfc21befab53c802376b21cc9 and before.

[INTERNAL] Restored IAccountManipulator#restoreDefaultAccount behavior

---

intellij/resources/META-INF/plugin.xml
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java

Adjusts the handling of local file property change events to correctly
filter out events triggered by a re-parsing of the file. This explicit
check is needed as such events are reported as re-namings onto the same
name, leading to issues in our logic (as this creates move activities
onto the same resource, resulting in a resource clash on the receiving
side).
This check is currently done by comparing the new and old name. Once
backwards compatibility is dropped below 2019.2, we should consider
using the dedicated method FilePropertyEvent.isRename() for this purpose
instead.
Fixes #740.
Amends the commented out list of plugin dependencies to adhere to the
plugin SDK guidelines.
The support for other JetBrains IDEs still remains disabled for now.
Even though the plugin now passes a smoke …

Drop re-parsing events

---

docs/assets/css/style.scss

The old selector `.tab-content :first-child` matched *all* elements that are the first child of their respective parent, such as the first list items in all lists. Furthermore, the intended padding was only added for the Eclipse tab (which was such a `:first-child`) but not the IntelliJ tab (which is always the second child, after the Eclipse tab).

[DOC] Correct CSS selector for gap between tab and content

---

docs/_includes/head.html

Sets the page or site title as the title in the HEAD section of the
generated HTML site. This allows the title to be displayed correctly in
the browser tab name.

[DOC] Set title in head

---

docs/contribute/development-environment.md

Updates the information on our use of the google java format tool to
specify that we are using version 1.6. Changes the links to the release
page to point to the specific release.
Updates the IntelliJ installation section to point to the workaround
used to run the google java format IntelliJ plugin for releases later
than 2018.2.
Remove reference to enabling google-java-format plugin for IntelliJ as
this is done by default.
Fixed typos.
Fixed name capitalization.

Update google java format info

---

docs/contribute/best-practices.md
docs/contribute/development-environment.md
docs/contribute/documentation.md
docs/contribute/guidelines.md
docs/contribute/html-gui.md
docs/contribute/open-topics.md
docs/contribute/processes/continuous-integration.md
docs/contribute/processes/development.md
docs/contribute/processes/release.md
docs/contribute/processes/review.md
docs/contribute/saros-server.md
docs/contribute/saros-testing-framework.md
docs/contribute/whiteboard.md
docs/documentation/faq.md
docs/documentation/features.md
docs/documentation/getting-started.md
docs/documentation/host-comic.md
docs/documentation/index.md
docs/documentation/saros-server.md
docs/documentation/setup-xmpp.md
docs/documentation/troubleshooting.md
docs/documentation/what-others-say.md
docs/index.md
docs/releases/saros-e_15.0.0.md
docs/releases/saros-i_0.2.0.md
docs/releases/saros-i_0.2.1.md
docs/research/index.md
docs/support/index.md

Correctly capitalizes the titles and headings for the website.
Fixes some minor typos and grammatical errors.

Fix title/heading capitalization

---

docs/documentation/saros-server.md

The Server was about the be released, when these lines were written, but the release was delayed until the next Saros/E release for an important bugfix. This commit reflects this in the documentation.
Fixes #762

[DOC] Remove server release link

---

README.md
docs/assets/images/logo/saros-logo.svg

Moves logo to the right.
Also uses an SVG version of the logo to allow the image to scale better.
This change is mostly a matter of taste. You can have a look at the result [here](https://github.com/saros-project/saros/blob/pr/doc/adjust_readme_logo_position/README.md).
I also considered a slightly different scaling that allows the first paragraph to fit into a single line. But that made the README look to cramped in my opinion. You can have a look at the other version [here](https://github.com/saros-project/saros/blob/test/README.md).
What are your thoughts? Do you prefer one version to the other?

[DOC] Change README logo position

---

eclipse/src/saros/editor/EditorManager.java
eclipse/src/saros/editor/internal/EditorAPI.java
eclipse/src/saros/project/FileActivityConsumer.java
eclipse/src/saros/project/ProjectDeltaVisitor.java
eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java

Preparation for fixing #758.
Adjusts the logic handling file deletion actions on the sending and
receiving side. Ensures that the editor for the deleted file is always
closed properly without saving.
Skipping the save is important as the editor will only still be open for
the deleted file if it was in an unsaved state at the time of deletion.
Closing such unsaved editors for deleted files is important as they
otherwise create issues with the consistency logic. Since the watchdog
logic is based on the open editors, the remaining editor is interpreted
as the resource still being present, leading to an inconsistent state.
Fixes #758.

Always close editor when file is deleted

---

docs/documentation/getting-started.md
docs/documentation/installation.md

Removes the old working referencing how to open the settings menu as it
was missing a modifier. The documentation now instead just references
the official IntelliJ help page on how to access the settings page.
In-band registration no longer works as it was disabled to protect
against abuse by spammers. This makes the "Create New Account..." button
in the Saros/E dialog no longer usable.
Adjusts the documentation to reflect this fact. Furthermore, it now
links to our signup page.

Minor installation guide adjustment

---

eclipse/src/saros/ui/expressions/ContactPropertyTester.java

ContactPropertyTester was using a direct call to smack roster.

[E] Replace Roster call with ContactsService

---

intellij/build.gradle

Sets the maximum JVM heap size to 2048m. This is needed to not run into
issues when loading/indexing larger projects. In particular, it is
needed to avoid issues when loading the Saros sources in a test
instance.

[BUILD][I] Adjust maximum heap size for 'runIDE' task

---

buildSrc/src/main/java/saros/gradle/eclipse/SarosEclipseExtension.java
stf.test/test/saros/stf/test/chatview/ChatViewFunctionsTest.java
stf.test/test/saros/stf/test/session/EstablishSessionWithDifferentTransportModesTest.java
stf/src/saros/stf/server/rmi/superbot/component/menubar/menu/submenu/impl/SarosPreferences.java
stf/src/saros/stf/shared/Constants.java
travis/script/stf/shared_vars.sh

After eclipse 4.6 the button "Ok" was
renamed to "Apply and Close".

Update to Eclipse 4.8

---

docs/documentation/saros-server.md

Adds a note that the Saros server has to be build manually if you would
like to use it before it is released with the next Saros/E minor
release. Also adds a note on the necessity to also build Saros/E to
access some server-related GUI features.
This was done to avoid future confusion on how to obtain a version of
the Saros server.

[DOC][S] Add information on building the Saros server yourself

---

eclipse/src/saros/ui/model/session/SessionContentProvider.java
eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java

Always open the UI contact list when a new contact was presented by the
XMPPContactsService. This fixes #796 where this wasn't done after
connecting (introduced with changes for ContactService) and also fixes
an older STF Problem / UI Problem when the list stayed collapsed due to
be empty before.

[E] Always Open Contact List for New Contact

---

docs/documentation/saros-server.md

Adjusts the Saros Server documentation to specify that a development
build of the Server will also require a development build of Saros/E to
run as there will otherwise be internal compatibility issues.

[DOC][S] Specify that Server dev build requires Saros/E dev build

---

intellij/src/saros/core/ui/eventhandler/UserStatusChangeHandler.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/util/MessageUtils.java

Such exceptions can actually be thrown if there is an entry in
Messages.java that is not present in the matching messages.properties
file.

Fix wrong message name introduced in refactoring #814

---

intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties
intellij/src/saros/intellij/ui/util/SafeDialogUtils.java
intellij/src/saros/intellij/ui/views/buttons/ConnectButton.java

Adds an entry "Create Account" to the connection menu.
The entry opens a dialog referring the user to our account creation
website.
The option was added to better guide users to the account creation
website and provide at least some kind of integration while we are not
able to provide in-plugin account creation.

[UI][I] Add "Create Account" entry referring to website

---

intellij/src/saros/intellij/editor/DocumentAPI.java

Adjusts the call to the command processor to execute document
modification in order to assure that the modification is only attributed
to the modified document and not also the currently selected/active
document.
This was done to prevent remote actions being attributed to the undo
stack of the currently selected document, even though the actions were
completely unrelated.
Fixes #819.

[FIX][I] #819 Only attribute undoable action to modified editor

---

core/src/saros/activities/DeletionAcknowledgmentActivity.java
core/src/saros/activities/FolderDeletedActivity.java
core/src/saros/activities/IActivityReceiver.java
core/src/saros/communication/extensions/ActivitiesExtension.java
core/src/saros/concurrent/jupiter/internal/Jupiter.java
core/src/saros/concurrent/management/ConcurrentDocumentClient.java
core/src/saros/concurrent/management/ConcurrentDocumentServer.java
core/src/saros/concurrent/management/DeletedResourceFilter.java
core/src/saros/concurrent/management/ResourceActivityFilter.java
core/src/saros/session/SarosCoreSessionContextFactory.java
core/src/saros/session/internal/ActivityHandler.java
core/src/saros/session/internal/DeletionAcknowledgmentDispatcher.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java

Adjusts ConcurrentDocumentClient and ConcurrentDocumentServer to drop
the vector time for a resource when it is deleted (or moved, thereby
"deleting" the resource with the previous path).
Adds DeletedResourceFilter to encapsulate the logic of detecting and
correctly handling resource deletions.
Furthermore, it provides a way of filtering out subsequent activities
for deleted resource.  This is needed as there can be straggling
activities for deleted resources that were created by remote
participants before they executed the deletion activity for the
resource.  Such activities are now filter out until the corresponding
resource is recreated.  This ensures that activities for the new
resource will still be processed correctly.
Checksum activities confirming the file deletion are explicitly …

Fix #223 - Drop vector time when resource is removed

---

buildSrc/src/main/java/saros/gradle/intellij/IntellijConfigurator.java
buildSrc/src/main/java/saros/gradle/intellij/SarosIntellijExtension.java
intellij/build.gradle

Removed the pluginName of the custom gradle plugin,
because wrapping the whole intellij plugin is not useful.
Set the pluginName properties to the new name.

[BUILD] Rename intellij zip to saros-intellij.zip

---

core/build.gradle
intellij/build.gradle

Fix #830
I tested:
* local execution
* import and build in IntelliJ
* import and build in Eclipse + launch config

[BUILD] Avoid redundant jars in intellij zip

---

.github/workflows/build.yml

Adjusts the logic modifying the plugin.xml to only run when building on
the master branch.
The plugin.xml is adjusted to enable compatibility with all JetBrains
IDEs for dev builds. Therefore, this adjustment is only needed when
actually publishing the artifacts, i.e. when building the master branch.
Otherwise, this is only included as a superfluous build step cluttering
up the log.

Enable gradle build scan for github workflow

---

.github/workflows/build.yml
.github/workflows/build_doc.yml

#315 Build documentation via GitHub pages.
In order to avoid that we introduce broken
documentation into the master branch, this
workflow builds the jekyll pages.

[BUILD] Build documentation

---

core/src/saros/editor/FollowModeManager.java

Removes the logic listening for text edits and adjusting the viewport
accordingly from the FollowModeManager.
As the comment on the corresponding method already states, the listener
is not necessary as the viewport will be updated anyways for the text
selection activity caused by the caret movement (that in turn is caused
by the text edit).
The only advantage this logic would offer is that it speeds up the
viewport adjustment. As the selection activity is processed after the
text edit activity, the text edit will be applied before the viewport is
adjusted. But, as the delay is very short and the edited text will be
highlighted anyways, this advantage is negligible.

[INTERNAL][CORE] Remove text edit listener from FollowModeManager

---

.idea/compiler.xml
stf.test/build.gradle

Remove superfluous configuration that causes issues in eclipse and IntelliJ
fix #859

[BUILD] Avoid duplicate content root entries

---

intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java
intellij/src/saros/core/ui/eventhandler/XMPPAuthorizationHandler.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/editor/DocumentAPI.java
intellij/src/saros/intellij/editor/EditorAPI.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/editor/annotations/AnnotationManager.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/ViewportAdjustmentExecutor.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
intellij/src/saros/intellij/runtime/EDTExecutor.java
intellij/src/saros/intellij/runtime/FilesystemRunner.java
intellij/src/saros/intellij/runtime/IntellijUISynchronizer.java
intellij/src/saros/intellij/ui/actions/ConsistencyAction.java
intellij/src/saros/intellij/ui/menu/ShareWithUserAction.java
intellij/src/saros/intellij/ui/util/NotificationPanel.java
intellij/src/saros/intellij/ui/util/SafeDialogUtils.java
intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java

This PR is mainly a refactoring, so there isn't a lot of interest happening. The main thing is moving the EDT runner logic from `Filesystem` to the new class `EDTExecutor` and then replacing direct calls to the EDT logic with calls to the new class.
Furthermore, a minor issue is fixed where calls in`ProjectAPI` were not run from the EDT even though they were required to.
Renames Filesystem to FilesystemRunner to better represent the
functionality of the class.
Subsequently moves it to the runtime package.
Adds the class EDTExecutor offering methods to synchronously or
asynchronously run tasks on the event dispatcher thread (EDT).
This class was added to unify the logic needing access to such
capabilities. A followup commit will replace all current usage of the
direct logic to run tasks on …

Refactor EDT handling

---

build.gradle
core/test/junit/saros/session/SarosSessionManagerTest.java
eclipse/test/junit/saros/SarosEclipseContextFactoryTest.java
eclipse/test/junit/saros/SarosEclipseContextTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java
intellij/test/junit/saros/intellij/context/SarosIntellijContextTest.java

Updates EasyMock and PowerMock to the newest compatible versions. This
was done to keep the number of issues related to java 11 to a minimum.
These annotations are necessary to avoid an internal issue with
powermock. This workaround will most likely become unnecessary at some
point in the future.
This was done to avoid an issue with the CTOR accessibility occurring
when using Java 11.

Prepare for update to Java 11

---

.github/workflows/build_jdk11.yml

In order to verify the compatibility of the Saros project
with JDK 11 we build the project each week with it.

[BUILD] Add jdk 11 cron build

---

core/src/saros/concurrent/jupiter/internal/text/SplitOperation.java
core/test/junit/saros/concurrent/SplitOperationTest.java

Fixes error in split operation combination logic dealing with two
insertions.
The existing logic incorrectly correlates the two insertions by the
start of the first and end of the second insertion and assumes that they
can then be combined.
When actually applying two activities matching this criteria, the
result, however, is not combinable:
```
Example: ins(5,"cd") + ins(3,"ab")
Start ins1 = 5
End ins2 = 5
-> Defined result: ins(3,"abcd)
Actual result when applying ins1 and ins2:
position  0123456789
start:   "          "
ins1:    "     cd   "
ins2:    "   ab  cd "
-> Does not match defined result
```
The actual result can not be defined through a single insertion as it is
not continuous.
Fixes the issue by instead requiring that both insertions have the same
start value.
```
Example: …
```

[FIX][CORE] Fix wrong split operation combination

---

intellij/src/saros/intellij/editor/DocumentAPI.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorHandler.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
intellij/src/saros/intellij/editor/ProjectAPI.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/EditorStatusChangeActivityDispatcher.java
intellij/src/saros/intellij/eventhandler/editor/editorstate/ViewportAdjustmentExecutor.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java

Adjusts the logic opening editors and using the obtained editor objects
to correctly handle null return values.
Adds missing Nullable annotations to the corresponding methods.
Adjusts the corresponding methods javadocs to better reflect the
possible return values in different cases.
Partial fix for #711.
Adjusts the logic to only save documents whose content has been
modified.
Adds the logic to check whether a document or virtual file is seen as
modified to the DocumentAPI.
This was introduced to avoid save operations on resources that can not
be represented by a document (e.g. binary files). Such cases are now
filtered out as such files will always be seen as unmodified by the API,
creating a better handling of such cases.
Adjusts the logic handling the user editor state of moved …

Fix handling of non-text editors

---

stf.test/build.gradle
stf.test/test/saros/stf/test/categories/FailingTests.java
stf.test/test/saros/stf/test/consistency/CreateSameFileAtOnceTest.java
travis/script/stf/master/start_stf_tests.sh

Removes the FailingTest tag from the CreateSameFileAtOnceTest as it
should be fixed with #867.
Closes #854.
Removes the category failing test as it is now no longer used.
Renames the test run from 'flakyAndFailingTest' to 'flakyTest'.

Remove failing test tag

---

build.gradle

In order to create a javadoc page, we have to ignore
the errors which are thrown because of our custom tags as
"@JTourBus".

[BUILD] Ignore javadoc errors during doc generation

---

eclipse/src/saros/editor/EditorManager.java
eclipse/src/saros/editor/internal/ContributionAnnotationHistory.java
eclipse/src/saros/editor/internal/ContributionAnnotationManager.java
eclipse/test/junit/saros/editor/internal/ContributionAnnotationHistoryTest.java
eclipse/test/junit/saros/editor/internal/ContributionAnnotationManagerTest.java

The PR splits all annotations in annotations of size 1 and removes the old splitting logic. This is much easier and fixes the issue. However, I would assume that this was the initial solution in Saros and the split logic was an optimization, but during my tests (manual and with stf) I had not the impression that my change worsens the user experiences.
Furthermore, this slightly changes the history handling, because text insertions are multiple annotation insertions. Therefore a long insertion is only annotated at the end. This leads to the question "How should this feature work?".
@srossbach What are your thoughts? Did I miss a corner case that requires the other handling?

Avoid not disappearing contribution annotations

---

intellij/src/saros/intellij/ui/menu/SarosFileShareGroup.java
intellij/src/saros/intellij/ui/tree/ContactPopMenu.java
intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java

To remove smack classes outside the core, this patch replaces the
roster logic with XMPPContactsService.

[I] Use XMPPContactsService instead of Roster

---

core/src/saros/concurrent/management/ResourceActivityFilter.java
core/src/saros/session/internal/DeletionAcknowledgmentDispatcher.java
intellij/src/saros/intellij/project/SharedResourcesManager.java

Such comments are no longer necessary as the vector time reset is
already completely handled in the core.
Fixes the deletion acknowledgement logic for the corner case where a
file move has the same origin and destination path. Even though such
cases were already ignored by the resource filtering logic, the deletion
acknowledgement logic was still sending acknowledgements, leading to
unnecessary warnings due to unexpected deletion acknowledgements.
Amends the javadoc of the corresponding methods to mention that such
move activities are ignored.

Fix minor issue with resource activity filter logic

---

core/src/saros/versioning/VersionManager.java
stf/src/saros/stf/server/StfRemoteObject.java
stf/src/saros/stf/server/rmi/superbot/internal/impl/InternalImpl.java

This patch updates the STF Superbot to correctly set a different Saros
version in VersionManager. This change is needed after changes on the
VersionManager logic in previous patches.
fixes #892

[STF] Update Version Set in STF Superbot

---

core/src/saros/communication/connection/ConnectionHandler.java
core/src/saros/communication/connection/IConnectingFailureCallback.java
eclipse/src/saros/ui/eventhandler/ConnectingFailureHandler.java
intellij/src/saros/intellij/context/SarosIntellijContextFactory.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/eventhandler/ConnectingFailureHandler.java
intellij/src/saros/intellij/ui/messages.properties

Adds the XMPP account used for the connection attempt to the failure
callback method. This makes it easier to pass this information to the
failure handlers.
Adjusts ConnectionFailureHandler to use the XMPP account passed by
IConnectingFailureCallback.connectingFailed(...).
Removes a null-check for the account that is now no longer necessary as
the connection logic calling the callback would have run into a NPE
beforehand.
Fixed a minor type in a variable name.
Adds a callback handler informing the user of a failed XMPP connection
attempt.
The previous handling just failed silently, leading to unnecessary
confusion.
The message handling was largely copied from the Saros/E counterpart to
this handler as it deals with specific network failure outcome messages.
Addresses usability issue …

Add connection failure callback handler

---

core/test/junit/saros/concurrent/jupiter/test/puzzles/GOTOInclusionTransformationTest.java
core/test/junit/saros/concurrent/jupiter/test/puzzles/InclusionTransformationFuzzingTest.java
core/test/junit/saros/concurrent/jupiter/test/puzzles/InclusionTransformationTest.java

Adds a fuzzing test for the inclusion transformation. The test generates
many random insert, delete, or split operations for either the client or
the server and periodically synchronizes the network and checks the
resulting document state.
The test was added to check for more subtle issues with the operation
transformation that might only occur with more complex transformation
chains.
The test also offers capabilities to reproduce certain result. At the
start of the test, the used seed is printed. If this seed is manually
set in the setup method, the fuzzer will run deterministicly in the same
fashion as the initial run.
As the test is not deterministic in its default setup, it is not
included in any test suite. It is meant to be run manually when changing
the transformation logic.
Adds …

Add inlcusion transformation fuzzer

---

core/src/saros/activities/TextEditActivity.java
core/src/saros/concurrent/jupiter/internal/text/DeleteOperation.java
core/src/saros/concurrent/jupiter/internal/text/GOTOInclusionTransformation.java
core/src/saros/concurrent/jupiter/internal/text/InsertOperation.java
core/src/saros/editor/text/TextPositionUtils.java
core/src/saros/util/LineSeparatorNormalizationUtil.java
core/test/junit/saros/editor/text/TextPositionUtilsTest.java
core/test/junit/saros/test/util/OperationHelper.java
eclipse/src/saros/editor/EditorManager.java
intellij/src/saros/intellij/editor/EditorManager.java
intellij/src/saros/intellij/editor/LocalEditorManipulator.java
server/src/saros/server/editor/Editor.java

Adds LineSeparatorNormalizationUtils offering utility methods to
normalize and denormalize the line separators for a given text.
This utility will be used in upcoming commits to normalize content
before passing it to the core, thereby allowing for a unified line
separator handling.
Adjusts the logic handling text edit activities to normalize line
separators before creating text edit activities and to revert the
normalization when applying received text edit activities.
No adjustment was necessary for Saros/I as the editors already work on
normalized Unix line separators.
This adds a new corner case that can lead to session desynchronizations
between two Saros/E instances: When two participants with different line
endings settings add content to an empty shared file, the line separator …

Introduce text edit content normalization

---

core/src/saros/concurrent/watchdog/ConsistencyWatchdogClient.java
core/src/saros/concurrent/watchdog/ConsistencyWatchdogHandler.java
core/src/saros/concurrent/watchdog/ConsistencyWatchdogServer.java
core/src/saros/editor/IEditorManager.java
eclipse/src/saros/editor/EditorManager.java
intellij/src/saros/intellij/editor/EditorManager.java
server/src/saros/server/editor/ServerEditorManager.java

Adds the method IEditorManager.getNormalizedContent(SPath). The method
provides access to normalized representations of the resource content,
i.e. the content only containing Unix line separators.
It is necessary for an upcoming adjustment of the consistency watchdog
logic to work with normalized resource contents.
Adjusts the consistency watchdog to use normalized file contents for
checksum creation. This is necessary as IntelliJ normalizes content line
endings internally, meaning the watchdog always works on normalized line
endings in Saros/I. For IDE cross-compatibility, other IDE
implementations must also use normalized content for the checksum
creation in order for the checksums to match correctly.
This also resolves an issue introduced with #877 where adding a newline
to an empty …

Adjust consistency watchdog to work with normalized content

---

.idea/encodings.xml

Sets UTF-8 as the default project encoding for newly created file.
Sets UTF-8 as the default project encoding for property files.

[I] Set UTF-8 as project default

---

core/src/saros/negotiation/FileListFactory.java

Removes the internal handling relying on FileListFactory objects, making
the class completely static. This was done to make it easier to inject
external dependencies from the plugin context. Furthermore, it makes the
class easier to understand.
Splits the method FileListFactory.addMembersToList(...) into a method
calculating the file list and a separate method calculating the
checksums for all contained files.
Adds javadoc for the new methods.
Removes unnecessary explicit type arguments.
Uses the list constructor accepting a collection instead of adding the
initial content separately.
Refactors the handling of metadata for files and folders to make it more
apparent that the metadata for folders is always null.

Clean up file list factory

---

intellij/src/saros/intellij/project/SharedResourcesManager.java

Checks whether the file move activity contained a content to use for the
new file. If so, uses the given content. Keeps the original content
otherwise.
This split handling is necessary as file moves are handled differently
by different IDEs. For Saros/E, the adjustments to the file as part of
the move are passed as the new content for the file. For Saros/I such
adjustments are send as additional text edit activities after the file
was moved.
With this adjustment, both handlings should be compatible with each
other.

[INTERNAL][I] Use content for file move activities

---

core/src/saros/filesystem/IResource.java
eclipse/src/saros/filesystem/EclipseResourceImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceRootImpl.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/session/FileActivityExecutor.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java
server/test/junit/saros/server/filesystem/ServerResourceImplTest.java

Replaces the usage of IResource.move(...) with explicitly creating the
new resource and then deleting the old resource. The new implementation
returns with a warning if the old resource to move does not exist. It
does not create the new resource in such cases.
This was done to remove the last (non-test) usage of IResource.move(...)
so that the method can be removed in a subsequent PR.
Removes the method IResource.move(...) and its implementations.
Removes all remaining usages of IResource.move(...) (only test cases).
The method was removed as it was only used by the Saros Server and is
not generally usable with the Saros resource model.
As the Server only operates on folders and the resource move
implementation is set up to handle absolute paths, it is technically
usable for the Server …

Remove IResource.move(...) method

---

core/src/saros/filesystem/FileSystem.java
core/src/saros/filesystem/IContainer.java
core/src/saros/filesystem/IFile.java
core/src/saros/filesystem/IFolder.java
core/src/saros/filesystem/IResource.java
core/src/saros/negotiation/AbstractIncomingProjectNegotiation.java
core/src/saros/negotiation/DecompressArchiveTask.java
core/src/saros/negotiation/stream/IncomingStreamProtocol.java
eclipse/src/saros/filesystem/EclipseContainerImpl.java
eclipse/src/saros/filesystem/EclipseFileImpl.java
eclipse/src/saros/filesystem/EclipseFolderImpl.java
eclipse/src/saros/filesystem/EclipseResourceImpl.java
intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceRootImpl.java
server/src/saros/server/editor/Editor.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/filesystem/ServerFolderImpl.java
server/src/saros/server/session/FileActivityExecutor.java
server/src/saros/server/session/FolderActivityExecutor.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java
server/test/junit/saros/server/filesystem/ServerFolderImplTest.java
server/test/junit/saros/server/filesystem/ServerResourceImplTest.java
server/test/junit/saros/server/filesystem/ServerWorkspaceImplTest.java

As a starting point for working on refactoring the file system implementation and migrating it to a reference point based model, I decided to clean up the existing interfaces first. This gives me the opportunity to get a better overview of the current interfaces and implementations. Furthermore, the simplified interfaces will make it easier to introduce the new resource logic down the line.
I would recommend reviewing this PR commit by commit as each commit contains changes regarding a separate topic. All commits should be relatively easy to understand as this PR mainly consists of basic refactorings.
<details><summary><b>[INTERNAL] Unify IFolder.create(...) methods</b></summary>
<br>
Removes the previous implementations of IFolder.create(...) and replaces
them by a single method create() …

Clean up resource interface

---

core/src/saros/filesystem/FileSystem.java
core/src/saros/filesystem/IResource.java
core/src/saros/negotiation/FileListFactory.java
core/src/saros/session/internal/SharedProjectMapper.java
core/test/junit/saros/negotiation/FileListTest.java
core/test/junit/saros/session/internal/SharedProjectMapperTest.java
eclipse/src/saros/filesystem/EclipseResourceImpl.java
eclipse/src/saros/filesystem/ResourceAdapterFactory.java
eclipse/test/junit/saros/project/FileActivityConsumerTest.java
intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceRootImpl.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/filesystem/ServerFolderImpl.java
server/src/saros/server/filesystem/ServerProjectImpl.java
server/src/saros/server/filesystem/ServerResourceImpl.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java
server/test/junit/saros/server/filesystem/ServerProjectImplTest.java
server/test/junit/saros/server/filesystem/ServerResourceImplTest.java

Replaces the list of integers specifying the different types of
resources with an enum. This makes the usage much easier and makes it
clear what to (and what not to) use the types for.
In general, it should be considered to replace the type concept as a
whole and work with instanceof checks instead.

Replace resource type list with enum

---

.github/workflows/build_doc.yml
docs/CNAME_template

Storing the CNAME file in the master branch
and deploying it into the gh-pages branch
led to the situation that the landing page was missing.
In order to avoid that we create the file only in the gh-pages.

[DOC] Create CNAME file in gh-pages

---

intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
intellij/src/saros/intellij/ui/wizards/JoinSessionWizard.java

Adjusts the cancellation listener in AddProjectToSessionWizard to only
close the dialog if the cancellation was caused by the remote side.
I am not really sure why the issue #923 occurred, but it seems to be a
race condition caused by CancelListener disposing the dialog at an
inconvenient moment.
The issue was introduced in ccf4111 by
removing the UIUtil.invokeLaterIfNeeded(...) block around the close()
call in cancelWizard(...).
This problem is now avoided by checking whether the cancellation was
caused locally as such cases are already handled by other logic.
Fixes #923.
Adjusts the JoinSessionWizard to automatically inform the user and close
when the session negotiation was aborted by the remote peer.

Fix local project negotiation cancel

---

eclipse/src/saros/filesystem/EclipseResourceImpl.java
intellij/src/saros/intellij/filesystem/IntelliJResourceImpl.java

Adjusts the IResource.isIgnored() implementations for Saros/E and
Saros/I to see any resource located in a '.git' directory and the
directory itself as ignored.
This is a temporary workaround to ensure that Saros does not destroy
data by overwriting the local git configuration as part of the project
negotiation.

[FIX] #922 Ignore .git directory for Saros sessions

---

docs/_includes/ide-tabs.html
docs/_sass/ide-tabs.scss
docs/assets/js/ide-tabs.js
docs/assets/main.scss

Extending the general .active
leads to inheriting the dark background.
It would be necessary to @extend .tab-content > .active.
However, the whole introduction of .active-tab was
a workaround for using the scrollspy (which is currently
not used). Therefore the default .active class is used.

[DOC] fix #935

---

stf.test/build.gradle

Use the gradle retry plugin for running the stf tests.
The current configuration lead to the behavior that:
* The test run fails if >= 10 tests failed in the first attempt (no retries, because
we assume that there is a real problem if so many tests are failing) 
* Tests that failed are repeated up to 3 times

[STF] Retry stf tests

---

core/src/saros/filesystem/IFile.java
eclipse/src/saros/filesystem/EclipseFileImpl.java
eclipse/src/saros/project/FileActivityConsumer.java
intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
server/src/saros/server/editor/Editor.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/session/FileActivityExecutor.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java

Improves the local handling of charsets for received file creation activities. Part of requirement for #912.
<details><summary><b>[API] Add IFile.setCharset(String)</b></summary>
<br>
Introduces IFile.setCharset(String). This method can be used to set the
character set for a file. It will be required for setting the correct
character set for resources created as part of the session creation once
this logic has been introduced.
Implements the method for Saros/E, Saros/I, and Saros/S.
The IFile.setCharset(String) implementation for Saros/E was largely
copied from FileActivityConsumer.updateFileEncoding(String,IFile). In an
upcoming change, the method updateFileEncoding will subsequently be
replaced with using IFile.setCharset(String).
</details>
<details><summary><b>[REFACTOR][E] Use …

Improve charset handling

---

core/src/saros/activities/FileActivity.java
eclipse/src/saros/project/ProjectDeltaVisitor.java
eclipse/src/saros/util/FileUtils.java
eclipse/test/junit/saros/project/FileActivityConsumerTest.java

Introduces the requirement for all file activities containing binary content to also contain a charset to use for that content. Adjusts Saros/E to always send a charset for such activities. Part of requirement for #912.
<details><summary><b>[INTERNAL][E] Adjust FileActivityConsumerTest to use file encoding</b></summary>
<br>
Adjusts the FileActivityConsumerTest to pass a specific file encoding
when creating a file activity. This was done in preparation of an
upcoming change requiring all file activities containing binary content
to also contain a valid encoding.
Introduces UTF-8 as the default chatset to use for the test. Explicitly
uses the charset for the string conversion instead of implicitly using
the JVM default charset.
Restructures the mocking logic to be able to mock internal …

Require charset for file activity containing binary content

---

core/src/saros/filesystem/IProject.java
eclipse/src/saros/filesystem/EclipseProjectImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
server/src/saros/server/filesystem/ServerProjectImpl.java
server/test/junit/saros/server/filesystem/ServerProjectImplTest.java

Removes the method `IProject.findMember(IPath)` and its implementations as
it was no longer being used (except in its own test cases). The last
usage was removed with the removal of `SPath`.
Furthermore, the removal of this class cleans up the concept of our
general resource interface handling as the method was the only one that
did not treat the local resources as handles, only returning them if
they were actually present in the local filesystem.

Remove IProject.findMember(IPath)

---

intellij/build.gradle
intellij/resources/META-INF/plugin.xml
intellij/src/saros/intellij/eventhandler/ProjectEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalClosedEditorModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandler.java
intellij/src/saros/intellij/eventhandler/editor/selection/LocalTextSelectionChangeHandler.java
intellij/src/saros/intellij/eventhandler/editor/viewport/LocalViewPortChangeHandler.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/negotiation/ModuleConfigurationInitializer.java
intellij/src/saros/intellij/ui/wizards/pages/moduleselection/ModuleTab.java
intellij/test/junit/saros/intellij/eventhandler/editor/document/LocalDocumentModificationHandlerTest.java

Sets the build target to IntelliJ Idea 2019.3.4.
Smoketest did not reveal any compatibility issues.
List of incompatible changes does not suggest any changes concerning
logic used by Saros/I.
I did not set the build target to 2020.1 as the update seems to have
introduced some changes to the filesystem handlers, the effects of which
have to be investigated further.
In particular, VirtualFileListener.beforeContentsChange(...) is now
often triggered without being caused by a save or a refresh. Such cases
are currently ignored by Saros but could be important events that we are
interested in.
Sets the new oldest supported IntelliJ IDEA version to 2019.2.3
(build 192.6817.14). This was done in order to not fall too far behind
the current release.
2019.2.3 was chosen as it is the earliest …

Bump minimal version support to 2019.2.3 and address deprecations

---

intellij/src/saros/intellij/editor/EditorManager.java

Adjusts the logic to save all files for a given IProject to simply save
all modified documents.
This adjustment is necessary as the previous implementation relied on
there being an open editor for modified documents. In IntelliJ, however,
documents are not automatically saved on closing the editor, meaning
there can be unsaved documents without an open editor. As a result, the
session negotiation could sometimes work on outdated file states,
leading to the wrong initial state on the receiving side.
Simply saving all documents is the lazy approach implementing this. It
would also have been possible to go through all unsaved documents and
check whether they belong to the given project. This is not necessary in
my opinion as there shouldn't be that many unsaved documents around,
especially …

[FIX][I] Save all documents on session start

---

intellij/src/saros/intellij/editor/annotations/AnnotationQueue.java
intellij/src/saros/intellij/editor/annotations/AnnotationRange.java

Adjusts the call AnnotationQueue.removeIfFull() to also remove the
dequeued annotation from the actual annotation mapping.
This was not causing any issues with the annotation logic as these
annotations no longer contain valid range highlighters, meaning they
would be removed from the annotation store when the corresponding editor
is closed. But this ensures that we only store annotations as long as
necessary to avoid any other potential issues with working on disposed
annotations and avoid unnecessary memory consumption.

Fix minor annotation manager issues

---

docs/package.json

Update jquery from 3.4.1 -> 3.5.1

[DOC] Bump jquery from 3.4.1 to 3.5.1

---

core/src/saros/filesystem/IContainer.java
core/src/saros/filesystem/IPathFactory.java
core/src/saros/filesystem/IProject.java
eclipse/src/saros/filesystem/EclipseContainerImpl.java
eclipse/src/saros/filesystem/EclipsePathFactory.java
eclipse/src/saros/filesystem/EclipseProjectImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/project/filesystem/PathFactory.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/src/saros/server/filesystem/ServerPathFactoryImpl.java
server/src/saros/server/filesystem/ServerProjectImpl.java

Adjusts the wording in `IPathFactory` to make it more clear that
`fromString(String)` takes a string representation of a path and not just
the name of a file.
Adjusts the methods of `IProject.getFile(String)` and `getFolder(String)` to
simply convert the given string into an `IPath` object and pass it to
`getFile(IPath)` or `getFolder(IPath)` respectively.
This already matched the implemented functionality of IntelliJ and the
Server. For Eclipse, the old implementation called the Eclipse method
`IProject.getFile(String)`, which actually searches for a file with the
given name in the project.
Renames the parameter of the methods to "pathString" instead of "name"
to reflect the new functionality.
Adjusts the javadoc of the methods to correctly describe their actual
functionality.
Moves the …

Move remaining methods from IProject to IContainer

---

intellij/src/saros/intellij/editor/annotations/AnnotationManager.java
intellij/test/junit/saros/intellij/editor/annotations/AnnotationManagerTest.java
intellij/test/junit/saros/intellij/editor/annotations/TestSuite.java

This PR adds test for all (public) methods in `AnnotationManager`. These test were added to cover the current (correct) behavior of the annotation manager to help with the refactoring #961 moving the functionality into the annotation objects to accommodate for caret annotations being part of the selection annotations.
To prepare for the testing logic, the methods in `AnnotationManager` to add and remove annotation ranges were also made static to make them easier to mock.
In general, I am not sure whether it is worth it investing a lot of time into reviewing the addition of a whole lot of test cases for the current behavior.
If you decide to have a closer look at the PR, I would suggest reviewing these changes commit-wise to make this at least somewhat reviewable. In general, the commits …

Add annotation mananger tests

---

intellij/src/saros/intellij/editor/annotations/AbstractEditorAnnotation.java
intellij/src/saros/intellij/editor/annotations/AnnotationManager.java
intellij/src/saros/intellij/editor/annotations/ContributionAnnotation.java
intellij/src/saros/intellij/editor/annotations/SelectionAnnotation.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/project/SharedResourcesManager.java
intellij/test/junit/saros/intellij/editor/annotations/AnnotationManagerTest.java

This PR moves most of the business logic dealing with updating the positioning and managing the contained ranges and range highlighters into the annotation objects. This was done to make it easier to implement further differences between the annotation types, in particular adding the caret annotation feature to the selection annotation (see feature request #367).
The methods are moved separately and tests are updated after every move to minimize the possibility of introducing a defect during the refactoring.
Continuation of #960.
I would suggest reviewing this PR commit by commit. The testing logic could get a bit ugly during the refactoring but should be somewhat cleaned up by the end.
<details><summary><b>[REFACTOR][I] Move addition adjustment logic into annotation object</b></summary> …

Move annotation update logic into annotation objects

---

.github/workflows/build_jdk11.yml
intellij/test/junit/saros/intellij/editor/annotations/AnnotationManagerTest.java

Adds the PowerMockIgnore annotations for "javax.swing.JComponent" to
avoid issues when mocking the IntelliJ interface Editor on Java 11.

[FIX][BUILD] Fixes issues with PowerMock and the Java 11 Build

---

core/src/saros/activities/TextSelectionActivity.java
core/src/saros/editor/text/TextSelection.java
intellij/src/saros/intellij/editor/EditorManager.java

Extends TextSelectionActivity to allow specifying the direction of the
selection. This was done to support backwards selections.
Adds a new constructor setting isBackwardsSelection=false by default to
allow for compatibility with implementations not supporting backwards
selections (yet).
Adds the requirement for the given selection range to be forwards facing
(start<=end) to allow for a unified handling of backwards selections.

Add support for backwards selections

---

docs/contribute/best-practices.md
docs/contribute/deprecated/html-gui.md
docs/contribute/documentation.md
docs/contribute/guidelines.md
docs/contribute/open-topics.md
docs/contribute/processes/review.md
docs/contribute/refactoring-filesystem.md
docs/contribute/saros-testing-framework.md
docs/documentation/awareness-information.md
docs/documentation/faq.md
docs/documentation/features.md
docs/documentation/getting-started.md
docs/documentation/installation.md

Adjusts the "Restrictions" section in the guide for starting a session
in Saros/I to feature headings instead of bold text. This was done so
that they also support smart anchors, making it easier to link to them.

Fix minor issues

---

intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java

Adds a check to the method generateResourceCreationActivitiy of
LocalFilesystemModificationHandler to ensure that the file is actually
open in a local editor before setting it up (which in turn would cause
such an editor to open).
The previous behavior of always setting up the editor for the created
file caused an issue where an editor was opened for resources created as
part of the project negotiation. This is due to the local filesystem
handler not being disabled during the project negotiation (as they are
not accessible to the core). As a result, the handler is called for file
creations that were the result of a received activity. To stop a
ping-pong of such activities, the dispatching of such activities is
dropped. The rest of the logic is still executed, part of which tries to
set up …

[FIX][I] Fix Saros opening editors for files created during negotiation

---

core/src/saros/activities/TextSelectionActivity.java

Adjusts TextSelectionActivity.getSelection() to correctly return
TextSelection.EMPTY_SELECTION if all selection values are -1.
Adds an exception if only some values are -1. This should in theory not
be possible as a valid handling of all >=0 or all ==-1 is enforced by
the TextSelection constructor.

[FIX][CORE] Fix handling of empty selection in text selection activity

---

.github/workflows/build.yml
intellij/resources/META-INF/plugin.xml

Declares the basic module dependencies in the Saros/I plugin.xml,
thereby declaring it as compatible with all JetBrains IDEs.
This was done as JetBrains no longer allows pushing new plugin versions
to the JetBrains Plugin Repository which don't declare any module
dependencies (i.e. are "legacy plugins").
As the compatibility with other JetBrains IDEs was planned after the
upcoming reference point migration anyway, rather then manually
declaring the dependency to other IntelliJ-specific modules, it seems
more sensible to allow the compatibility now and inform the users that
compatibility with other JetBrains IDEs is not well tested (but should
generally work).
Plugin verification and smoke tests with CLion, PyCharm, WebStorm, and
Rider did not reveal any issues. The plugin verifier run of …

Mark Saros/I as compatible with all JetBrains IDEs

---

core/src/saros/versioning/Version.java
core/test/junit/saros/versioning/VersionManagerTest.java

Adjusts the version compatibility logic to only check for major and
minor versions and ignore micro/patch versions. This allows us to push
out bugfix releases without breaking compatibility without having to
first implement a more sophisticated version compatibility logic.

[INTERNAL][API] Ignore micro/patch version for compatibility check

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
README.md
docs/_data/releases/current.yml
docs/_data/releases/sidebar.yml
docs/contribute/development-environment.md
docs/contribute/saros-testing-framework.md
docs/documentation/faq.md
docs/documentation/getting-started.md
docs/documentation/how-tos/change-colors.md
docs/documentation/how-tos/manage-xmpp-accounts.md
docs/documentation/index.md
docs/documentation/installation.md
docs/releases/index.md
docs/releases/saros-i_0.3.0.md

Updates all mentions of the current Saros/I release to 0.3.0.
Adds the release notes page for release 0.3.0.
Bumps the release version badge displayed on the README.md page to
0.3.0.
Adjusts the documentation to reflect that 'Saros for IntelliJ' is now
compatible with all JetBrains IDEs. (We might have to think about
changing the name to make this easier.)
Tries to replace mentions of 'IntelliJ' with 'JetBrains' where sensible
or specify that other JetBrains IDEs are supported as well.
Replaces mentions of 'IntelliJ IDEA' with just 'the IDE' when talking
about interacting with the IDE the plugin is running on.

[I] Adjust documentation for release 0.3.0

---

build.gradle

Marks the build artifacts for the documentation as excluded to avoid
them being shown in the IDE search.

[BUILD][I] Mark doc build artifacts as excluded

---

core/src/saros/filesystem/IContainer.java
core/src/saros/negotiation/FileListFactory.java
core/test/junit/saros/negotiation/FileListTest.java
eclipse/src/saros/filesystem/EclipseContainerImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/filesystem/ServerProjectImpl.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java
server/test/junit/saros/server/filesystem/ServerProjectImplTest.java

~~Might still need to be adjusted. Currently, merging this PR would break the server as the project encoding is used as the default for file encodings. This issue would be resolved by implementing #912. Another option would be to add a default handling to the server file implementation until #912 is resolved. (As a result of the change, this would also mean that the server would have to persist the encodings or would no longer be able to add a project to the session.)~~ Added temporary workaround until #912 is resolved.
~~This PR also removes the addition of the project default encoding from the file list. This might still be useful for compatibility checks during before executing the project negotiation on the remote side. So this PR might be adjusted to just move the method …

Remove IContainer.getDefaultCharset()

---

core/src/saros/filesystem/IWorkspace.java
eclipse/src/saros/filesystem/EclipseWorkspaceImpl.java
intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceImpl.java
server/src/saros/server/console/ShareCommand.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/src/saros/server/filesystem/ServerFileImpl.java
server/src/saros/server/filesystem/ServerFolderImpl.java
server/src/saros/server/filesystem/ServerProjectImpl.java
server/src/saros/server/filesystem/ServerResourceImpl.java
server/src/saros/server/filesystem/ServerWorkspaceImpl.java
server/src/saros/server/session/NegotiationHandler.java
server/test/junit/saros/server/filesystem/FileSystemTestUtils.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java
server/test/junit/saros/server/filesystem/ServerFileImplTest.java
server/test/junit/saros/server/filesystem/ServerFolderImplTest.java
server/test/junit/saros/server/filesystem/ServerProjectImplTest.java
server/test/junit/saros/server/filesystem/ServerResourceImplTest.java
server/test/junit/saros/server/filesystem/ServerWorkspaceImplTest.java

Refactors the Server resource handling to use ServerWorkspaceImpl
directly. This was done to allow the methods 'getProject()' and
'getLocation()' to be removed from the interface without having to
adjust the server implementation.
Removes the methods IWorkspace.getProject() and getLocation() as they
were no longer being used in the core.

Clean up IWorkspace

---

core/src/saros/filesystem/IFile.java
core/src/saros/filesystem/IFolder.java
core/src/saros/filesystem/IProject.java

Overwrites specific methods of IContainer in IProject to specify the
differing behavior for projects.
Adds default implementations for specific methods in IProjects that have
a constant behavior.
Adds default implementations of getType() for IProject, IFile, and
IFolder returning the corresponding type.

Add default resouce methods

---

intellij/src/saros/intellij/ui/messages.properties

Adds a comment to ignore the "Unused Property" warning in the
messages.properties files. This is necessary as IntelliJ does not detect
the fields as being used as they are injected through the use of
reflections.

[INTERNAL][I] Ignore "Unused Property" warning in messages.properties

---

core/src/saros/filesystem/IContainer.java

Adjusts the javadoc of IContainer.getFolder(...) to not allow empty
paths. Returning the called-on object works for IFolder objects but not
for other IContainer implementations (like IProject).

[API][CORE] Adjust IContainer.getFolder(...) to not allow empty paths

---

core/src/saros/communication/chat/AbstractChatService.java
core/src/saros/communication/chat/IChat.java
core/src/saros/communication/chat/IChatServiceListener.java
core/src/saros/communication/chat/muc/MultiUserChatService.java
core/src/saros/net/util/XMPPUtils.java
eclipse/src/saros/communication/chat/muc/negotiation/MUCNegotiationManager.java
eclipse/src/saros/ui/widgets/chat/ChatControl.java
eclipse/src/saros/ui/widgets/chat/ChatRoomsComposite.java

Instead of leaking the XMPPException class in ChatServiceListener out
of core, return a error message.
This is not ideal, but removes another explicit XMPPException reference.
Use the always available defaultConnectionService, which is the same as the one passed.

Small Smack Simplifications

---

build.gradle
core/src/saros/communication/connection/ConnectionHandler.java
core/src/saros/editor/colorstorage/ColorIDSetStorage.java
core/src/saros/negotiation/IncomingSessionNegotiation.java
core/src/saros/negotiation/OutgoingSessionNegotiation.java
core/src/saros/session/internal/LeaveAndKickHandler.java
eclipse/src/saros/ui/actions/ChangeXMPPAccountAction.java
eclipse/src/saros/ui/eventhandler/NegotiationHandler.java
eclipse/src/saros/ui/preferencePages/GeneralPreferencePage.java
eclipse/src/saros/ui/widgets/ColorChooser.java
intellij/src/saros/core/monitoring/Status.java
lsp/src/saros/lsp/SarosLanguageServer.java
ruleset.xml
server/src/saros/server/session/JoinSessionRequestHandler.java
stf/src/saros/stf/client/tester/RealTester.java

I propose to use one static code analysis tool per language (instead of multiple that are currently enabled)
with a corresponding configuration/ruleset-file that allows enabling the checks in the IDE.
Therefore, I created an initial PMD file that only contains the "Unused*" rules.
(The GitHub Action integration is just for showing the violations. AFAIK codacy
uses only ruleset files that are already on the master branch.)
There are currently ~40 violations of these rules. We should:
* Fix the violations
* Mark the rule as required
* Enhance the ruleset in the future (PMD's [best-practices ruleset](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html) is a good starting point)

[BUILD] Create initial PMD ruleset

---

.github/workflows/build_pmd.yml

Adds the GitHub workflow build_pmd which is run on any push or pull
request matching the branch name 'pr/pmd/**' or modifying the pmd
ruleset file.
This action ensures that the PMD ruleset applies without any issues
before merging onto master. This is necessary as Codacy, which runs our
PMD checks, only uses the ruleset file of the master branch.

[BUILD] Add workflow running PMD on changes to the ruleset

---

.github/workflows/build_pmd.yml
buildSrc/src/main/java/saros/gradle/intellij/IntellijConfigurator.java
core/test/junit/saros/negotiation/FileListDiffTest.java
core/test/junit/saros/net/internal/DataTransferManagerTest.java
intellij/src/saros/intellij/ui/eventhandler/ConnectingFailureHandler.java

* Fix pmdTest violations
* Fix new violation
@stefaus I changed the method in ConnectionFailureHandler from private to public. Probably `@SuppressWarnings` is a better solution or implementing the interface via lambda. What do you think?

[BUILD] Fix remaining "Unused*" violations

---

eclipse/plugin.xml

PR #1010 also changed the name of the used
eclipse endpoint from `preferencesPages` -> `preference_pages`
(which is not an existing endpoint).
Fixes #1014

[INTERNAL][STF] Fix wrong eclipse endpoint

---

core/src/saros/filesystem/IContainer.java
core/src/saros/negotiation/FileListFactory.java
core/test/junit/saros/negotiation/FileListTest.java
eclipse/src/saros/filesystem/EclipseContainerImpl.java
intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
server/src/saros/server/filesystem/ServerContainerImpl.java
server/test/junit/saros/server/filesystem/ServerContainerImplTest.java

Adjusts IContainer.members() to return a list instead of an array. This
simplifies the implementation and usage of the method which previously
required multiple conversions into an array and back into a list.

[API][CORE] Return list for IContainer.members()

---

intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java
intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java
intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java
intellij/src/saros/intellij/filesystem/IntelliJResourceImpl.java
intellij/src/saros/intellij/filesystem/IntellijFileImplV2.java
intellij/src/saros/intellij/filesystem/IntellijFolderImplV2.java
intellij/src/saros/intellij/filesystem/IntellijReferencePointImpl.java
intellij/src/saros/intellij/filesystem/IntellijResourceImplV2.java
intellij/src/saros/intellij/filesystem/VirtualFileConverter.java

Introduces the new reference point based resource implementation. The
implementation is based on the existing implementation that was then
simplified and adjusted to use reference points.
The new implementation is not used anywhere yet.
Marks the old resource implementations as deprecated.
Adds methods for the new reference point based resource implementations
to VirtualFileConverter.
Marks the old methods as deprecated.

Introduce reference point resources (ref-point migration 1/5)

---

intellij/src/saros/core/ui/util/CollaborationUtils.java
intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java
intellij/src/saros/intellij/ui/Messages.java
intellij/src/saros/intellij/ui/messages.properties

Migrates the logic handling local filesystem modifications to the new reference point based resource implementation. Adjust the logic to correctly handle specific edge-cases of the new resource system.
<details><summary><b>[INTERNAL][I] Migrate filesystem handler to support new sharing logic</b></summary>
<br>
Removes all references to the old sharing logic/resource implementation.
Adjusts the logic to ignore moves/renames of reference point base
resources.
Removes no longer necessary, module specific logic and TODOs.
Adjusts the file filter to only filter out excluded files. Even
filtering out excluded resources is merely a performance optimization
and may be removed in the future.
</details>
<details><summary><b>[INTERNAL][I] Leave …

Migrate local resource handler to reference points (ref-point migration 5/5)

---

gradle/wrapper/gradle-wrapper.properties

Adjusts the gradle wrapper configuration to also download the gradle
sources. Downloading the sources as well allows IDEs to automatically
link the documentation for gradle methods used in the build.gradle
files.

[BUILD] Include grade sources when downloading gradlew

---

travis/script/stf/master_setup_utils.sh

Eclipse dropped the GTK2 support [with 4.10](https://www.eclipse.org/eclipse/news/4.10/platform.php#gtk2-removal).
Our build process uses the latest compatible
bundle version (and the corresponding [new jar](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt/3.114.100) was released at 17.06.20).
Therefore, the new bundle version is used and we have to install GTK3.
However, this installation has to be moved into
a Dockerfile file in the corresponding repository.
I will open a follow-up PR.

[BUILD] Workaround failing STF Tests

---

core/src/saros/communication/connection/ConnectionHandler.java
core/src/saros/communication/connection/IConnectionStateListener.java
eclipse/src/saros/service_providers/SarosSourceProvider.java
eclipse/src/saros/ui/actions/ChangeXMPPAccountAction.java
eclipse/src/saros/ui/widgets/ConnectionStateComposite.java
eclipse/src/saros/ui/widgets/chat/ChatRoomsComposite.java

Moves XMPP exception parsing into Core and `IConnectionStateListener` now returns an `ErrorType` enum instead of an `Exception`.

Move XMPP Exception Parsing into Core

---

core/src/saros/session/SarosSessionManager.java
core/src/saros/session/internal/SarosSession.java
core/test/junit/saros/session/SarosSessionManagerTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java

Avoids the dependency on the connection service to initialize the
session context by passing the JID of the local user to the session
constructor.
Removes the method to resolve plugin context dependencies from
SarosSession as it was no longer necessary. Moved the error handling
in-line for the last usage.
Updates the session tests for the new CTOR argument.

[INTERNAL][CORE] Pass JID of local user to session CTOR

---

core/src/saros/session/SarosSessionManager.java
core/src/saros/session/internal/SarosSession.java
core/test/junit/saros/session/SarosSessionManagerTest.java
eclipse/test/junit/saros/session/internal/SarosSessionTest.java

The desired effect can be done without annotations and IIRC in former times fields could be null instead of throwing an exception. As this is up to the implementation do it the correct way.

[INTERNAL][CORE] Remove annotation injection from SarosSession

---

docs/contribute/development-environment.md

Oracle does not provide a public JDK 8 version.
Therefore, we provide a link to alternative sources.

[DOC] Add info where to get a JDK8

---

eclipse/src/saros/filesystem/EclipseContainerImpl.java
eclipse/src/saros/filesystem/EclipseFileImplV2.java
eclipse/src/saros/filesystem/EclipseFolderImpl.java
eclipse/src/saros/filesystem/EclipseFolderImplV2.java
eclipse/src/saros/filesystem/EclipseProjectImpl.java
eclipse/src/saros/filesystem/EclipseReferencePointImpl.java
eclipse/src/saros/filesystem/EclipseResourceImpl.java
eclipse/src/saros/filesystem/EclipseResourceImplV2.java
eclipse/src/saros/filesystem/ResourceAdapterFactory.java
eclipse/src/saros/filesystem/ResourceConverter.java

This is my current draft for the new Eclipse resource implementation. The details of the implementation might still change a bit if I encounter any trouble while migrating Saros/E to the new resource implementation but should be stable in general.
A full review of the class is not sensible quite yet (as it still might change), but I would appreciate some feedback on the general design of the implementation.
Adds new resource implementation based on the reference point model.
The new resource implementation somewhat resembles the new IntelliJ
resource implementation. This is due to both implementations now
operating on the same resource model and being bound by the same
restrictions (i.e. the Eclipse implementation now also having to deal
with relative resources instead of solely relying …

[INTERNAL][E] Introduce reference point based resource implementation

---

travis/script/stf/coordinator_setup_utils.sh
travis/script/stf/shared_vars.sh

Use the new images (tag 0.8) containing a GTK3
installation and remove the workaround introduce with #1047.

[BUILD][STF] Use new docker images

---

.github/workflows/build.yml

Replaces the "set-env" call in the build workflow with writing the
parameter to the GITHUB_ENV file. The old way of setting environment
variables is deprecated and will be removed in the future.

[BUILD] Replace set-env in build workflow

---

eclipse/src/saros/concurrent/undo/UndoManager.java
eclipse/src/saros/editor/EditorManager.java
eclipse/src/saros/editor/EditorPool.java
eclipse/src/saros/editor/RemoteWriteAccessManager.java
eclipse/src/saros/editor/internal/EditorAPI.java
eclipse/src/saros/editor/internal/SharedDocumentProvider.java
eclipse/src/saros/filesystem/EclipsePathFactory.java
eclipse/src/saros/filesystem/EclipseWorkspaceImpl.java
eclipse/src/saros/filesystem/checksum/EclipseAbsolutePathResolver.java
eclipse/src/saros/filesystem/checksum/FileContentNotifierBridge.java
eclipse/src/saros/project/FileActivityConsumer.java
eclipse/src/saros/project/FolderActivityConsumer.java
eclipse/src/saros/ui/util/CollaborationUtils.java
eclipse/src/saros/util/EclipseCollaborationUtilsImpl.java
eclipse/test/junit/saros/project/FileActivityConsumerTest.java
stf/src/saros/stf/server/rmi/superbot/component/view/eclipse/impl/PackageExplorerView.java

Migrates the internal logic of Saros/E to use the new resource model introduced in #1023. The UI and filesystem handler logic is migrated separately in follow-up PRs. Outdated javadoc and method names that are not directly related to the changed logic will be updated in a separate clean-up PR at the end.
Most of the changes made in this PR are relatively simple as they just replace the usage of the old resource implementation with the new one and usage of the `ResourceAdapterFactory` with `ResourceConverter`.
I would suggest reviewing this PR commit by commit. 
<b>[INTERNAL][E] Migrate FolderActivityConsumer to new resource impl</b>
<details><summary><b>[INTERNAL][E] Partially migrate CollaborationUtils to new resource impls</b></summary>
<br>
Migrates the internal logic of …

Migrate internal classes to use new resource implementation (ref-point migration 1/10)

---

eclipse/src/saros/project/ProjectDeltaVisitor.java
eclipse/src/saros/project/SharedResourcesManager.java
eclipse/src/saros/session/resources/validation/ResourceChangeValidator.java
eclipse/src/saros/session/resources/validation/ResourceDeltaVisitor.java

Migrates the filesystem handler logic of Saros/E to use the new resource model introduced in #1023. Outdated javadoc and method names that are not directly related to the changed logic will be updated in a separate clean-up PR at the end.
<details><summary><b>[INTERNAL][E] Migrate ResourceDeltaVisitor to new resource impls</b></summary>
<br>
Adjusts the logic to check for reference points instead of projects.
</details>
<details><summary><b>[INTERNAL][E] Skip non-shared resources for ResourceDeltaVisitor</b></summary>
<br>
Adjusts ResourceChangeValidator to only check resource deltas for the
shared reference points. This avoid iterating all non-shared resources.
Adjusts ResourceDeltaVisitor to get passed the reference point to use.
This …

Migrate filesystem handlers to use new resource implementation (ref-point migration 2/10)

---

eclipse/src/saros/ui/widgets/viewer/project/BaseResourceSelectionComposite.java
eclipse/src/saros/ui/widgets/viewer/project/ResourceSelectionComposite.java
eclipse/src/saros/ui/wizards/AddResourcesToSessionWizard.java
eclipse/src/saros/ui/wizards/StartSessionWizard.java
eclipse/src/saros/ui/wizards/pages/ResourceSelectionWizardPage.java

Migrates the logic to select which resources to start a resources negotiation with of Saros/E to use the new resource model introduced in #1023. Outdated javadoc and method names that are not directly related to the changed logic will be updated in a separate clean-up PR at the end.
Completely rewrites the wizard to select local resources to start a resource negotiation with. The new implementation still uses the old tree model to avoid having to introduce even more new logic. This somewhat worsens the usability as the current tree model does not allow disabling elements. As a result, "illegal" changes are just reverted internally as we can't stop the user from interacting with the tree nodes. See issue #1041. …

Migrate sender resource selection logic to use new resource implementation (ref-point migration 4/10)

---

eclipse/src/saros/ui/command_handlers/SessionAddProjectsHandler.java
eclipse/src/saros/ui/command_handlers/SessionAddSelectedProjectsHandler.java
eclipse/src/saros/ui/menu_contributions/StartSessionWithProjects.java
eclipse/src/saros/ui/util/CollaborationUtils.java
eclipse/src/saros/ui/wizards/AddResourcesToSessionWizard.java
eclipse/src/saros/ui/wizards/StartSessionWizard.java

Migrates parts of the internal UI logic of Saros/E to use the new resource model introduced in #1023. Outdated javadoc and method names that are not directly related to the changed logic will be updated in a separate clean-up PR at the end.
This is the second part of the internal UI migration.
<details><summary><b>[INTERNAL][E] Migrate CollaborationUtils.startSession(...)</b></summary>
<br>
Migrates CollaborationUtils.startSession(...) to work on a set of
reference points. Adjusts the usages of the method to correctly supply a
set of reference points.
</details>
<details><summary><b>[INTERNAL][E] Migrate CollaborationUtils.addResoucesToSession(...)</b></summary>
<br>
Renames the method to addReferencePointsToSession(...) to make it more …

Migrating ui internals to new resource implementation 2/3 (ref-point migration 5/10)

---

core/src/saros/filesystem/IReferencePoint.java
core/src/saros/session/internal/SharedReferencePointMapper.java
eclipse/src/saros/filesystem/EclipseReferencePoint.java
intellij/src/saros/intellij/filesystem/IntellijReferencePoint.java
server/src/saros/server/filesystem/ServerProjectImpl.java

Adds a sanity check ensuring the no nested reference points can be created. As this is only a sanity check, it does not provide the best user experience. Nested reference points should be prevented by the IDE-specific UI not allowing such resource choices when starting or receiving resource negotiations.
<details><summary><b>[INTERNAL] Add method to check for nested reference points</b></summary>
<br>
Adds IReferencePoint.isNested(IReferencePoint), providing the logic to
check whether the given reference point would create a nested
configuration with the called-on reference point.
Adds the IDE implementations for the new method.
</details>
<details><summary><b>[INTERNAL][CORE] Add sanity check preventing nested reference …

Add sanity check to prevent nested reference points

---

eclipse/src/saros/resource_change_handlers/ToStringResourceDeltaVisitor.java
eclipse/src/saros/ui/widgets/wizard/ReferencePointOptionComposite.java
eclipse/src/saros/ui/widgets/wizard/ReferencePointOptionResult.java
eclipse/src/saros/ui/wizards/AddReferencePointsToSessionWizard.java
eclipse/src/saros/ui/wizards/pages/LocalRepresentationSelectionPage.java

Fixes issues with the paths used in the context of the local Saros instance.
<details><summary><b>[FIX][E] #1093 Correctly display path of existing resource for error</b></summary>
<br>
Adjusts the error message displayed in cases where the user chooses the
option to create a new directory as part of the resource negotiation
using values pointing to an already existing directory. The message used
the `toString()` of the `IContainer` object which included a resource type
designation at the start of the path. To avoid confusion, the
OS-specific path of the resource is used instead.
Resolves #1093.
</details>
<details><summary><b>[INTERNAL][E] Use OS path when exclusively working in the local context</b></summary>
<br>
Replaces usages of `IPath.toPortableString()` with `IPath.toOSString()` …

Fixes issues with the paths used in the context of the local Saros instance

---

buildSrc/build.gradle.kts
intellij/build.gradle.kts
intellij/resources/META-INF/plugin.xml
intellij/src/saros/intellij/context/IntellijVersionProvider.java
intellij/src/saros/intellij/eventhandler/ProjectEventHandlersFactory.java
intellij/src/saros/intellij/eventhandler/editor/viewport/LocalViewPortChangeHandler.java
intellij/src/saros/intellij/ui/SarosToolWindowFactory.java

Sets the minimal compatibility of the plugin to IntelliJ 2020.1.3.
Increases the minimal supported IntelliJ version to 2020.1.3 (build ID
201.8538.31).
Adjusts the build setup to use this version when starting IntelliJ
instances for local test builds.
Corrects the usages of deprecated APIs now possible with the minimal
supported IntelliJ version 2020.1.
Replaces the usage of `PluginManager.getPlugin(...)` with
`PluginManagerCore.getPlugin(...)`.
Adds the project the handler belongs to as the disposable parent for
`LocalViewPortChangeHandler`.

Move minimal compatibility to 2020.1

---

intellij/src/saros/intellij/editor/BackgroundEditorPool.java
intellij/src/saros/intellij/editor/ProjectAPI.java

Adjusts the BackgroundEditorPool to correctly drop all background
editors associated with the closing project. This is necessary as they
will otherwise be detected as a memory leak.
This case should normally be handled as part of the session teardown
triggered by ProjectClosedHandler. But the session teardown is executed
asynchronously on a different thread, meaning it only takes effect after
the internal memory leak check of IntelliJ has already run.
Adjusts the method creating the background editors offered by ProjectAPI
to also accept a project parameter to associate with the editor. This is
necessary to request the corresponding project from the editor. Even if
the editor is not explicitly associated with the project, it is still
connected to it and must be torn down as part of the …

[FIX][I] Correctly tear down BackgroundEditorPool for closing project

---

intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java
intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java
intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java

Adjusts the Saros view to correctly display the initial state at the
point it was initialized. This is necessary as the view relies on
listeners to correctly update the state. As a result, it will not be
able to reflect changes that were made before it was initialized.
To avoid this issue, the components are manually initialized with the
initial state.
This is more of a quick fix than an actual solution. The whole Saros
view logic needs an overhaul as the state handling is spread across
multiple classes, making it very hard to track.
Resolves #1050.

[FIX][I] #1050 Correctly initialize Saros view

---

eclipse/META-INF/MANIFEST.MF
eclipse/feature/feature.xml
eclipse/update/site.xml
server/src/saros/server/SarosServer.java

Increases the Saros/E version to 16.0.1 to match the current release.
This change was probably never merged back into the master when the
release was created.
Adjusts the version number of the Saros Server to match the current
Saros/E release number.
This should have been done when the release was published but was
forgotten.

Fix version numbers

---

core/src/saros/versioning/Compatibility.java
core/src/saros/versioning/Version.java
core/src/saros/versioning/VersionCompatibilityResult.java
core/src/saros/versioning/VersionManager.java
core/test/junit/saros/versioning/VersionManagerTest.java
docs/_data/documentation/sidebar.yml
docs/documentation/compatibility.md
docs/releases/index.md

Adjusts the Saros version compatibility logic. Adds a separate check ensuring that the entire version string matches (including micro and qualifier) when a qualifier is given as part of the version. This ensures that users can't start a session between different development builds. Subsequently cleans up the version compatibility logic.
Adds a specific page describing the Saros version compatibility to the homepage. Also adds a section mentioning the development builds to the releases page.
<details><summary><b>[INTERNAL][CORE] Add compatibility result for differing dev builds</b></summary>
<br>
Adds a compatibility result indicating that at least one of the compared
versions contained a qualifier and the version strings did not match
exactly. As the qualifier is the indicator that a …

Check for qualifier as part of version compatibility check

---

eclipse/build.gradle.kts
stf/build.gradle.kts

This is a temporary fix for #1114, which can be used to compile Saros/E with JDK version 8.
This is not a proposed solution and the workaround will need to be updated for every `org.eclipse.platform`, that we use and gets an update at this point. Actually discussion about long-term fixes should be done in #1114.

Workaround for compiling Saros/E with Java 8

---

docs/contribute/development-environment.md

which previously did not work because it targeted .jar instead of .java files.

[DOC] Fix google-formatter-command in dev docs

---

intellij/src/saros/intellij/editor/annotations/AbstractEditorAnnotation.java
intellij/src/saros/intellij/editor/annotations/AnnotationHighlighterLayers.java
intellij/src/saros/intellij/editor/annotations/ContributionAnnotation.java
intellij/src/saros/intellij/editor/annotations/SelectionAnnotation.java
intellij/test/junit/saros/intellij/editor/annotations/AnnotationManagerTest.java

Adjusts the Saros editor annotation highlighter layer. The annotations
are now displayed at a very low level, meaning they will be overshadowed
by almost all other IDE highlighters. This will ensure that the user
will still be able to develop normally using the default IDE features
while in a Saros session.
Separates the different annotations onto different highlighter layers to
create the correct hierarchy. This ensures that selection annotations
overshadow contribution annotations to match the behavior of Saros/E.
It looks a bit weird that the line selection highlighter now also
overshadows Saros annotations. But it provides an important visual aid
to keep track of the current caret position, so I wanted to avoid
overshadowing it. But this is something that can easily be fixed if user …

[FIX][I] #962 Adjust Saros annotation highlighter layer

---

.github/workflows/build.yml
.github/workflows/build_doc.yml
.github/workflows/build_pmd.yml
.github/workflows/stf.yml

Improves the run conditions for the existing GitHub actions.
Adjusts the GitHub action configuration to only run on Pull Requests and
on pushes to the 'master' branch. This avoids the actions always running
twice for PRs, once for the PR and once for the push to the branch.
Adjusts the STF GitHub action to run on any PR that modifies resources
in the 'core', 'eclipse', 'stf', or 'stf.test' directory. This should
ensure that the action is run for any PR that modifies resources that
could influence the result of the STF.

Improve action run conditions

---

intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java
intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java
intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java

Introduces new methods to reload the entire tree model or a specific
node while trying to retain the current tree expansion. To do so, the
model saves all expanded paths before the reload and restores them after
the reload.
Replaces all calls to reloading the model with calls to the new utility
methods to ensure that the expansion state is preserved as part of the
reload.
Moves the responsibility of reloading the contacts node for session
related events (e.g. when hiding a contact from the contacts list when
they join the current session) to the contacts node class.
Replaces calls to expanding specific rows of the tree with calls to
expanding the path of the element that is actually supposed to be
expanded. This removes the guesswork whether the given row actually
points to the correct …

Fix Saros view update behavior

---

intellij/src/saros/intellij/ui/menu/SarosResourceShareGroup.java
intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java
intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java
intellij/src/saros/intellij/ui/views/buttons/FollowButton.java

Adjusts different part of the Saros UI to always sort the displayed contacts alphabetically.
Also adjusts the display logic for the users of the current session in the Saros view to display the 'Host' label in bold and italics to better differentiate it from the user name.
Adds logic to sorts the contacts displayed in the contacts view
alphabetically.
Resolves #610.
Sorts the user nodes displayed in the session view alphabetically. Also
ensures that the entry for the session host is always displayed as the
first user, independent of the user name.
Adjusts UserInfo to display the 'Host' label in bold and italics. This
should help user better differentiate between the label and the display
name of the user.

Sort contact names

---

eclipse/build.gradle.kts
stf/build.gradle.kts

This is a temporary fix for #1138.
This is not a proposed solution and the workaround will most probably need to be updated for coming versions of `org.eclipse.platform:org.eclipse.ui.ide` (the version of which is also part of another workaround, see [here](https://github.com/saros-project/saros/pull/1115)). Actually discussion about long-term fixes should be done in #1138.

[BUILD] Workaround for build fail
