saros-project/saros

.travis.yml
Activate that Travis CI sends mails if a build fails
=> [BUILD] Enable travis notifications on failure

de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/AbstractIncomingProjectNegotiation.java, de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ArchiveIncomingProjectNegotiation.java, de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ArchiveOutgoingProjectNegotiation.java, de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/negotiation/ProjectNegotiation.java, de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/actions/SendFileAction.java
Reverts saros-project/saros#127
@srossbach still required changes on this PR. Therefore we have to revert this PR
=> Revert "[INTERNAL] Move Transfer Listener Logic"

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJProjectImplV2.java
Moves the check whether the given module has exactly one content root in
the CTOR of IntelliJProjectImplV2 to a separate method.
Also improves the message of the thrown exception if there is not
exactly one content root and adds @throws tags for the exception to the
CTOR javadoc.
=> [INTERNAL][I] Move content root check to separate method

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/annotations/AnnotationManager.java
Adds a check when creating range highlighters to ensure that the end
position is not located after the document end. This can happen during a
desync between participants. If the documents are no longer the same
length due to the desync, a participant could edit or select parts of
the document with an illegal offset for other participants.
=> [FIX][I] Add check if annotations violate document bounds

de.fu_berlin.inf.dpp.ui/src/de/fu_berlin/inf/dpp/ui/View.java, de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/IHTMLBot.java, de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/htmlbot/impl/HTMLBotImpl.java, de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/IRemoteHTMLView.java, de.fu_berlin.inf.dpp.ui/test/framework/stf/src/de/fu_berlin/inf/dpp/stf/server/rmi/remotebot/widget/impl/RemoteHTMLView.java, de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/AddContactTest.java, de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/ComponentViewTest.java, de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/MainViewTest.java
I extracted the view Enum from IRemoteHTMLView to a new file. Also i
removed that View-Key map and build fields on the enum.
Change-Id: I830e92428b7840ff2b1dfe5ea5dc87ab2a8c4834
=> [STF][RREFACTOR] Extract view enum

de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/session/FileActivityExecutor.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/session/FolderActivityExecutor.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/session/ServerSessionContextFactory.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/session/TextEditActivityExecutor.java
Applies Activities onto the local filesystem of the Server. (Finally does not trigger the `ConsistencyWatchdog` anymore).
=> [FEATURE][SERVER] Add ActivityExecutors

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/ui/menu/SarosFileShareGroup.java
The project pop-up menu entry to share modules now uses the same logic
as the ContactPopMenu and AddProjectToSessionWizard to determine whether
a module can be shared or not.
=> [FIX][I] Use new sharing rules for project pop-up menu share button

de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/ServerConfig.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/ServerContextFactory.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/session/NegotiationHandler.java
Adds an `INegotiationHandler` to the Server, required to participate in sessions.
=> [FEATURE][SERVER] Add NegotiationHandler

de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/SarosServer.java, de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/ServerLifecycle.java
Now that the server is able to do something meaningful (at least once #144 is merged), actually start a session.
=> [FEATURE][SERVER] Start session

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java, de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/FileSystemChangeListener.java, de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/project/SharedResourcesManager.java
Completely rewrites the handling of local filesystem activities. Since this is a rather large change, it is split into multiple commits to make the review process a bit easier.
=> [I] Rewrite FileSystemChangeListener

.idea/uiDesigner.xml
Adds the default ui-designer configuration file that is automatically
generated by IntelliJ.
=> [I] Add default uiDesigner.xml automatically created by IntelliJ

de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorAPI.java, de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorManager.java, de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/EditorPool.java, de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/editor/LocalEditorManipulator.java
Fixes UserEditorState initialization with `[FIX][I] Fix UserEditorState initialization`.
Does some cleanup with the other commits.
=> Fix UserEditorState initialization

de.fu_berlin.inf.dpp.whiteboard/frontend/package.json
set the version of the breaking terser library to an older version.
once the problem is fixed this can be removed.
=> [INTERNAL][HTML WB] fix #418

docs/assets/css/style.scss, docs/contribute/development-environment.md, docs/contribute/guidelines.md, docs/documentation/faq.md, docs/documentation/getting-started.md, docs/documentation/host-comic.md, docs/documentation/setup-xmpp.md, docs/documentation/troubleshooting.md, docs/downloads/index.md
* Fixed #450 
* Fixed table format (e.g. [here[(http://saros-project.github.io/saros/contribute/guidelines.html#commit-message))
* Added code highlighting to multiple code boxes
=> [DOC] Fix multiple documentation issues

eclipse/src/saros/ui/widgets/ConnectionStateComposite.java
This patch ensures that the connection widget is updated when either the
account file changes or accounts are added.
=> [UI][E] Update ConnectionState on account changes

ui.frontend/html/src/components/ContextMenu/Component.jsx, ui.frontend/html/src/components/ContextMenu/Controller.jsx, ui.frontend/html/src/components/Focusable/FocusableItem.jsx, ui.frontend/html/src/components/Focusable/FocusableMenu.jsx, ui.frontend/html/src/components/MainView/ActiveAccount.jsx, ui.frontend/html/src/components/MainView/RunningSession.jsx, ui.frontend/html/src/index.jsx, ui.frontend/html/src/stores/SarosStore.jsx, ui.frontend/html/src/styles/style.css, ui.frontend/html/src/template.ejs, ui.frontend/html/test/utils.js
the menu is currently just a container with some elements for testing purposes, but will be expanded later.
in the patch two new components have been added: `FocusableItem` and `FocusableMenu` which provide the ability to control the focus with the mouse as well as with the keyboard.
these components have been used in the `Running Session` component to make it also more accessible.
also some stylistic changes
=> [INTERNAL][HTML] Add a context menu

core/src/saros/account/XMPPAccountStore.java, core/src/saros/editor/colorstorage/ColorIDSetStorage.java, core/test/junit/saros/account/XMPPAccountStoreTest.java
* Cleaned up the tests of XMPPAccountStore
* Used XStream in order to (de)serialize XMPPAccount and ColorIDSet
#491
=> Rework serialization of XMPPAccount and ColorIDSet

docs/_data/contribute/sidebar.yml, docs/_includes/navbar.html, docs/_layouts/index.html, docs/contribute/development-environment.md, docs/documentation/installation.md
See commit messages for more information.
=> Minor adjustments to documentation

.idea/compiler.xml
Adds the compiler config adjustment that is done automatically by
IntelliJ when building the project.
=> [BUILD][I] Commit automatic compiler config adjustment

.idea/misc.xml
This PR adjusts the change introduced in #291 to the new picocontainer
package name introduced in #365.
=> [I] Replace code analyzer exception with new picocontainer reference

intellij/src/saros/intellij/context/SarosIntellijSessionContextFactory.java, intellij/src/saros/intellij/context/SharedIDEContext.java, intellij/src/saros/intellij/editor/EditorManager.java, intellij/src/saros/intellij/eventhandler/ApplicationEventHandlers.java, intellij/src/saros/intellij/eventhandler/ApplicationEventHandlersFactory.java, intellij/src/saros/intellij/eventhandler/IApplicationEventHandler.java, intellij/src/saros/intellij/eventhandler/IEventHandler.java, intellij/src/saros/intellij/eventhandler/IProjectEventHandler.java, intellij/src/saros/intellij/eventhandler/IStartableDisableableHandler.java, intellij/src/saros/intellij/eventhandler/ProjectEventHandlers.java, intellij/src/saros/intellij/eventhandler/ProjectEventHandlersFactory.java, intellij/src/saros/intellij/eventhandler/editor/document/AbstractLocalDocumentModificationHandler.java, intellij/src/saros/intellij/eventhandler/editor/editorstate/AbstractLocalEditorStatusChangeHandler.java, intellij/src/saros/intellij/eventhandler/editor/editorstate/AnnotationUpdater.java, intellij/src/saros/intellij/eventhandler/editor/editorstate/EditorStatusChangeActivityDispatcher.java, intellij/src/saros/intellij/eventhandler/editor/editorstate/PreexistingSelectionDispatcher.java, intellij/src/saros/intellij/eventhandler/editor/editorstate/ViewportAdjustmentExecutor.java, intellij/src/saros/intellij/eventhandler/editor/selection/LocalTextSelectionChangeHandler.java, intellij/src/saros/intellij/eventhandler/editor/viewport/LocalViewPortChangeHandler.java, intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java, intellij/src/saros/intellij/project/SharedResourcesManager.java
Looks like a lot of code, but most of the changes are minor refactorings or the addition of simple data holder classes and their factories.
The PR should by reviewed by going through the commits. Each commit features a commit message giving more details about the content.
=> Prepare to remove project from plugin context (6 of X)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
In order to induce people to provide more detailed reports I created a bug and a feature report template.
=> Create Bug/Feature report and PR template

docs/_data/contribute/sidebar.yml, docs/contribute/open-topics.md
This documentation references interesting PRs
which are closed, because they are not complete
or the approach was not usable.
=> [DOC] Create documentation of open topics

docs/contribute/open-topics.md
=> [DOC] Open Topics of Instant Session Start

core/src/saros/concurrent/management/HeartbeatDispatcher.java
The Heartbeat dispatcher forgot to register the listener and so the fireActivity call was also a NoOp as well.
=> [FIX][CORE] #580 Heartbeat causes vectortime desync 

ui/src/saros/ui/browser/AbstractJavascriptFunction.java, ui/src/saros/ui/browser/IBrowser.java, ui/src/saros/ui/browser/NoCheckedExceptionCallable.java, ui/src/saros/ui/browser/SWTBrowser.java
* IBrowser: an interface to abstract
from the browser logic.
* SWTBrowser: an implementation of
IBrowser for the SWT Browser
* JavascriptFunction and NoCheckedExceptionCallable
as in the swt browser improved
Extracted the used logic of the swt-browser-improved
=> [INTERNAL][HTML] Introduce IBrowser and SWTBrowser

stf.test/test/saros/stf/test/html/AddContactTest.java
Fix wrong enum in AddContactTest
=> [STF] Fix wrong enum value in AddContactTest

eclipse/src/saros/ui/wizards/pages/ConfigurationSettingsWizardPage.java
This patch fixes issue #456 by changing the focus logic.
In addition it no longer uses the EmptyText wrapper as this wrapper will
still show the default value if the delegate is disabled but not text
was inserted at all. In addition the default empty text was not helpful
at all. I would expect some example but it simply read "Skypename". This
is what this WizardPage asks you to insert ...
=> [FIX][E] #456 Strange behavior in Configuration Settings Page

core/src/saros/account/XMPPAccountStore.java, eclipse/src/saros/ui/messages.properties, eclipse/src/saros/ui/preferencePages/GeneralPreferencePage.java, stf/src/saros/stf/server/rmi/controlbot/manipulation/IAccountManipulator.java, stf/src/saros/stf/server/rmi/controlbot/manipulation/impl/AccountManipulatorImpl.java, stf/src/saros/stf/server/rmi/superbot/component/menubar/menu/submenu/impl/SarosPreferences.java, stf/test/saros/stf/test/stf/menubar/SarosPreferencesTest.java
Includes several fixes for defects introduced by PR #608 
This PR also updates test cases that where failing because of the general changes made by PR #609
=> [INTERNAL] Addresses issues introduced with PR #608

eclipse/src/saros/communication/SkypeManager.java, eclipse/src/saros/ui/actions/SkypeAction.java, eclipse/src/saros/ui/views/SarosView.java
This patch enables the Skype feature again. Reworked most of the
SkypeManager logic by just throwing away code.
=> [INTERNAL][E] Enables SkypeManager

core/src/saros/net/xmpp/subscription/SubscriptionHandler.java, core/src/saros/net/xmpp/subscription/SubscriptionListener.java
Add the possibility to listen to subscription canceled events.
=> [CORE] Add Subscription Canceled Listener

eclipse/test/junit/saros/ui/model/roster/RosterComparatorTest.java
To start removing Smack from UI packages, remove it from test classes.
=> [JUNIT][E] Remove Smack Roster from Test

eclipse/src/saros/StartupSaros.java
The URL was already dead. Also this web page gives no hint on how to
open this wizard.
=> [UI][E] Show configuration wizard on startup

core/src/saros/session/internal/ActivityHandler.java
It is now stopped with a poison pill to avoid some issues in some
UISynchronizer implementations.
=> [INTERNAL][CORE] Stop ActivityHandler more gracefully

stf/.settings/org.eclipse.jdt.core.prefs
=> [BUILD] Sets Java version for Eclipse IDE to 8 for project saros.stf

core/src/saros/concurrent/management/HeartbeatDispatcher.java
This patch addresses the FIXMEs. In addition it adds a detailed
description from the original Jupiter paper why it is necessary to
generate NoOps.
Refactored the dispatchHeartbeats method to make it more readable.
=> [INTERNAL][CORE] Addresses FIXMEs in HeatbeatDispatcher

eclipse/src/saros/ui/Messages.java, eclipse/src/saros/ui/messages.properties, eclipse/src/saros/ui/wizards/ConfigurationWizard.java, eclipse/src/saros/ui/wizards/pages/AddContactWizardPage.java
Replaced it depending on the context.
This patch also fix an issue where the AddContactWizard could be
finished without entering a JID.
=> [UI][E] #22 Removes the wording Jabber

eclipse/src/saros/ui/actions/ChangeXMPPAccountAction.java
The default account is no longer changed when switching accounts with
the account action. However the action will remember the last used
account and uses it until the whole IDE is restarted.
=> [INTERNAL][E] Prevents overriding the default account

eclipse/src/saros/editor/EditorPool.java
Basically all document providers that do not extend from
TextFileDocumentProvider (like XText) are likely not to work with Saros.
Even retrieving the document provider from the editor will not help us
as we also operating in headless mode. Otherwise we would have to open
editors on the fly and so disturbing the user experience.
As we cannot do much about this issue for now log at least a message.
=> [INTERNAL][E] Logs warnings for incompatible editors.

eclipse/test/junit/saros/test/mocks/EditorManagerMock.java
Added a minimal behavior to the editor manager mock.
=> [TEST][E] Addresses #497

core/src/saros/net/upnp/internal/UPnPServiceImpl.java, core/src/saros/net/xmpp/XMPPConnectionService.java, core/src/saros/session/internal/ActivityHandler.java, core/src/saros/session/internal/ActivitySequencer.java, core/src/saros/session/internal/LeaveAndKickHandler.java, core/src/saros/session/internal/timeout/ClientSessionTimeoutHandler.java, core/src/saros/session/internal/timeout/ServerSessionTimeoutHandler.java, core/src/saros/session/internal/timeout/SessionTimeoutHandler.java, core/src/saros/synchronize/StopManager.java, core/src/saros/util/NamedThreadFactory.java, core/src/saros/util/ThreadUtils.java, core/test/junit/saros/util/NamedThreadFactoryTest.java, eclipse/src/saros/Saros.java, eclipse/src/saros/ui/preferencePages/NetworkPreferencePage.java, eclipse/src/saros/ui/sounds/SoundPlayer.java, eclipse/src/saros/ui/util/XMPPConnectionSupport.java, eclipse/src/saros/ui/widgets/chat/ChatRoomsComposite.java, eclipse/src/saros/ui/wizards/JoinSessionWizard.java, eclipse/src/saros/ui/wizards/pages/ConfigurationSettingsWizardPage.java, server/src/saros/server/synchronize/ServerUISynchronizerImpl.java, stf/src/saros/stf/StartupSarosSTF.java, whiteboard/src/saros/whiteboard/sxe/net/SXEIncomingSynchronizationProcess.java
Adds "saros-" as Thread Name Prefix and minor changes.
Remove old Thread Prefix, because its now added by ThreadUtils and
NamedThreadFactory.
=> Cleanup Thread Naming

docs/documentation/getting-started.md
=> [DOC][I] Amend color wording in Getting Started page

docs/_data/contribute/sidebar.yml, docs/_data/documentation/sidebar.yml, docs/contribute/saros-server.md, docs/documentation/saros-server.md
Please, check that:
Some initial docs for Saros-Server in preparation of the first release.
Feel free to correct any spelling-mistakes / etc and make suggestions.
=> Add some initial Saros-Server documentation

core/src/saros/concurrent/watchdog/ConsistencyWatchdogHandler.java, core/src/saros/session/ISarosSession.java, core/src/saros/session/SarosCoreSessionContextFactory.java, core/src/saros/session/internal/ActivityHandler.java, core/src/saros/session/internal/SarosSession.java
Also removed the access through the ISarosSession interface.
=> [FIX] #719 Remove 'ConcurrentDocumentServer' from client session context

intellij/build.gradle
Did minimal smoke test that did not reveal any issues. Minor releases
should not cause compatibility issues anyways.
=> [BUILD][I] Update build IntelliJ version to 2019.2.4

intellij/src/saros/intellij/editor/EditorManager.java, intellij/src/saros/intellij/editor/LocalEditorHandler.java, intellij/src/saros/intellij/eventhandler/project/ProjectClosedHandler.java, intellij/src/saros/intellij/negotiation/ModuleConfigurationInitializer.java, intellij/src/saros/intellij/negotiation/hooks/ModuleTypeNegotiationHook.java, intellij/src/saros/intellij/ui/tree/SessionTreeRootNode.java
This PR contains some adjustments to IReferencePoints
=> [I]Some adjustments to IReferencepoints

docs/documentation/faq.md
Please, check that:
- [~] all commits comply with our [commit message guidelines](https://www.saros-project.org/contribute/guidelines.html#commit-message)
- [~] your code complies with the google java format (see [here](https://www.saros-project.org/contribute/development-environment.html) for details) or ESLint configuration
- [~] all unit tests are still successful
A link in the FAQ was outdated. This might be a good replacement.
=> Update saros-for-intellij link

docs/documentation/getting-started.md, docs/documentation/installation.md
Amend wording on installation page to no longer claim that we are still
on the first alpha release.
Fix typo on getting started page.
=> [DOC][I] Fix minor issues in used doc

docs/contribute/development-environment.md
Add information about sandbox directory environmental variable.
Adjust wording.
=> Update development setup guide

docs/contribute/processes/review.md, docs/documentation/getting-started.md
Adjusts some remaining pictures to scale correctly when viewed on
mobile.
=> Scale images correctly when viewed on mobile

eclipse/src/saros/ui/menuContributions/StartSessionWithProjects.java, eclipse/src/saros/ui/model/roster/RosterCheckStateProvider.java, eclipse/src/saros/ui/model/roster/RosterComparator.java, eclipse/src/saros/ui/widgets/viewer/session/HideContactsInSessionFilter.java, eclipse/src/saros/ui/wizards/pages/ContactSelectionWizardPage.java
Remove some javadoc refs avoiding smack imports.
=> [E] Remove Simple Roster References

eclipse/src/saros/ui/views/SarosView.java
Replace the RosterListener with IContactsUpdate and use IPropertyChangeListener to get sound settings.
=> Replace RosterListener in SarosView

intellij/src/saros/intellij/negotiation/ModuleUtils.java
Uses VfsUtil.toUri(String) to correctly parse the "URL" returned by
getUrl() calls on VFS objects.
This is needed as the "URI" format does not adhere to the standard on
Windows machines, leading to issues when trying to parse it directly.
This is discussed in the PR #704 and the IntelliJ bugtracker entry
"https://youtrack.jetbrains.com/issue/IDEA-146869".
Fixes #703. Adjustment of initial fix PR #704.
=> [FIX][I] #703 Use IntelliJ util to parse URI

core/src/saros/net/xmpp/contact/AddContactUtility.java, core/src/saros/net/xmpp/contact/XMPPContactsService.java, eclipse/src/saros/ui/wizards/AddContactWizard.java
This patch basically moves the existing add Contact logic into the core contact package.
=> Move Add Contact Code to Core

core/src/saros/net/xmpp/contact/XMPPContactsService.java, eclipse/src/saros/ui/wizards/pages/AddContactWizardPage.java
To avoid direct roster calls, a new method is introduced to retrive
contact objects via XMPPContactsService.
=> [CORE][E] Get XMPPContacts by JID

.idea/compiler.xml, .idea/gradle.xml
Adds automatic changes to the IntelliJ project settings following the
addition of the VSC project addition.
=> [I] Commit automatic changes to IntelliJ settings

docs/documentation/getting-started.md, docs/documentation/installation.md, docs/documentation/screenshots.md
Adjusts the initial offset of the continued enumeration blocks so that
the correct values are displayed.
Removed unnecessary blank lines in lists.
Makes intended breaks in lists more clear.
Fixes old list layout now no longer supported by markdown.
=> Minor fixes for lists/enumerations in documentation

docs/contributing.md
Contribute to #199 
In order to avoid to maintain the same content in `docs/contribute` and in the new file
I  wrote a short summary with (I hope so) the most important information and links to the
extensive description.
=> [DOC] Add Contributing.md

core/src/saros/net/IPacketInterceptor.java, core/src/saros/net/internal/XMPPTransmitter.java, core/src/saros/session/internal/ActivitySequencer.java, stf/src/saros/stf/server/rmi/controlbot/manipulation/impl/NetworkManipulatorImpl.java
It now uses the transmitter instead of the connection to send packets
which caused issues because the content was not compressed although it
should.
=> [INTERNAL][STF] NetworkManipulator should work again

intellij/src/saros/intellij/ui/Messages.java, intellij/src/saros/intellij/ui/messages.properties, intellij/src/saros/intellij/ui/widgets/progress/ProgressMonitorAdapter.java, intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
~~Better solution for issue discovered as part of #674.~~
~~Early WIP for the patch. Currently only contains some refactorings. More meant as a reminder that this topic still exists.~~
Minor cleanup for `ProgressMonitorAdapter`.
=> Clean up ProgressMonitorAdapter

intellij/src/saros/core/monitoring/IStatus.java, intellij/src/saros/intellij/context/SarosIntellijContextFactory.java, intellij/src/saros/intellij/context/SharedIDEContext.java, intellij/src/saros/intellij/editor/BackgroundEditorPool.java, intellij/src/saros/intellij/editor/EditorAPI.java, intellij/src/saros/intellij/editor/EditorManager.java, intellij/src/saros/intellij/editor/LocalEditorHandler.java, intellij/src/saros/intellij/editor/LocalEditorManipulator.java, intellij/src/saros/intellij/editor/annotations/AbstractEditorAnnotation.java, intellij/src/saros/intellij/editor/colorstorage/ColorManager.java, intellij/src/saros/intellij/filesystem/IntelliJFileImpl.java, intellij/src/saros/intellij/filesystem/IntelliJFolderImpl.java, intellij/src/saros/intellij/filesystem/IntelliJProjectImpl.java, intellij/src/saros/intellij/negotiation/ModuleConfigurationProvider.java, intellij/src/saros/intellij/negotiation/hooks/ModuleTypeNegotiationHook.java, intellij/src/saros/intellij/preferences/PropertiesComponentAdapter.java, intellij/src/saros/intellij/preferences/colors/LocalSarosAnnotationColorsPage.java, intellij/src/saros/intellij/project/filesystem/IntelliJPathImpl.java, intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceImpl.java, intellij/src/saros/intellij/project/filesystem/IntelliJWorkspaceRootImpl.java, intellij/src/saros/intellij/ui/menu/SarosFileShareGroup.java, intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java, intellij/src/saros/intellij/ui/util/UIProjectUtils.java, intellij/src/saros/intellij/ui/views/buttons/AbstractSessionToolbarButton.java, intellij/src/saros/intellij/ui/wizards/pages/NavigationPanel.java, intellij/src/saros/intellij/util/MessageUtils.java
Adds missing final modifiers.
Removes unused variables and methods.
Removes unnecessary modifiers (e.g. in interfaces).
Fixes typos.
Fixes unresolvable javadoc references.
Removes unnecessary explicit type declarations.
Replaces raw usages of generic classes by adding a wildcard type
argument.
Removes unnecessary throws clauses.
Replaces anonymous inner classes with lambda expressions.
Replaces declarations of specific charsets with references to the
standard charset implementations.
=> [REFACTOR][I] Fix minor miscellaneous issues

.github/ISSUE_TEMPLATE/bug_report.md, docs/documentation/getting-started.md
=> [DOC][I] Update log location in bug reporting guideline

buildSrc/src/main/java/saros/gradle/intellij/IntellijConfigurator.java
Added a warning to all exceptions thrown by us.
(as discussed in #724)
=> [BUILD] Add race condition info to runIde exception

docs/_includes/scripts.html, docs/_sass/header-anchor-links.scss, docs/assets/js/header-anchor-links.js, docs/assets/main.scss
=> [DOC] Add smart anchor

intellij/src/saros/intellij/editor/EditorAPI.java, intellij/src/saros/intellij/editor/EditorManager.java, intellij/src/saros/intellij/eventhandler/editor/selection/LocalTextSelectionChangeHandler.java, intellij/test/junit/saros/intellij/editor/EditorAPITextPositionTest.java
=> Support backwards selections

intellij/build.gradle, intellij/resources/META-INF/plugin.xml
Updates the change notes in the plugin.xml.
Bumps the plugin version specified in the Saros/I build.gradle file to
0.3.0.
Formats the Saros/I plugin.xml according to the IntelliJ default format
using 2 spaces as the indentation width.
=> Prepare release 0.3.0

core/META-INF/MANIFEST.MF, eclipse/META-INF/MANIFEST.MF, eclipse/feature/feature.xml, eclipse/update/site.xml
Cherry-picked the version updates of the rc-16.0.0 branch.
=> Update eclipse & core version

eclipse/src/saros/ui/wizards/dialogs/ConfigurationWizardDialog.java
=> [UI][E] Fix ConfigurationWizard's "Next" Button

stf.test/test/saros/stf/test/roster/SortContactsOnlineOverOfflineTest.java
The order check should use the same comparison logic (ignore case).
=> [STF] Ignore case during contact order check

docs/contribute/development-environment.md
=> [DOC] Add eclipse version restriction to dev-env

.github/workflows/stf.yml, run_stf.sh, stf/build.gradle.kts, travis/script/stf/coordinator/start_stf_self_tests.sh, travis/script/stf/coordinator/start_stf_tests.sh
* Update the self test execution script
* Improve run_stf.sh to execute the self
tests and proper argument handling
* Allows "arguments" input in stf.yml
to run the STF job with arguments "--self"
to execute the self tests:
=> [BUILD] Integrate stf self tests into CI

eclipse/build.gradle.kts
=> [BUILD] Workaround missing dependency

stf/build.gradle.kts
=> [BUILD] Workaround missing dependency (STF)

core/src/saros/filesystem/IResource.java
Removes the ROOT resource type as it is no longer being used.
=> [NOP][CORE] Remove the ROOT resource type

server/src/saros/server/console/ConsoleCommand.java, server/src/saros/server/console/InviteCommand.java, server/src/saros/server/console/ServerConsole.java, server/src/saros/server/console/ShareCommand.java
Please, check that:
This commit adds a `minArgument` integer to `ConsoleCommands` for improved usage printing
and avoid wrong "Command '%s' is not known" messages.
The goal of this commit is to improve the usability of the CLI.
Thank you!
=> [UI][S] adds minArgument check to ConsoleCommands

intellij/src/saros/intellij/ui/tree/ContactTreeRootNode.java
Adjusts the Saros view contacts section to always display the currently
online contacts first. Matches the Saros/E behavior.
=> [UI][I] Display online contacts first

docs/releases/saros-i_0.3.0.md
Add some whitespace and remove a bit of wordiness.
=> [DOC] Improvements on Saros/I 0.3.0 release page

.github/workflows/build_doc.yml, docs/package.json
Update of the mermaid Library to fix several security concerns.
Update of the doc build script, because it contains deprecated and unsupported versions.
=> [DOC] Update doc build script and lib versions
